apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: memcached
    app.kubernetes.io/instance: rhobs
    app.kubernetes.io/name: api-memcached
    app.kubernetes.io/part-of: rhobs
    prometheus: app-sre
  name: api-memcached
  namespace: openshift-customer-monitoring
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - rhobs-production
  selector:
    matchLabels:
      app.kubernetes.io/component: memcached
      app.kubernetes.io/instance: rhobs
      app.kubernetes.io/name: api-memcached
      app.kubernetes.io/part-of: rhobs
