apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: thanos-operator
    app.kubernetes.io/instance: thanosstore-editor-role
    app.kubernetes.io/managed-by: rhobs
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: thanos-operator
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: thanos-operator-thanosstore-editor-role
rules:
- apiGroups:
  - monitoring.thanos.io
  resources:
  - thanosstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.thanos.io
  resources:
  - thanosstores/status
  verbs:
  - get
