apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: memcached
    app.kubernetes.io/instance: rhobs
    app.kubernetes.io/name: thanos-bucket-cache
    app.kubernetes.io/part-of: rhobs
    app.kubernetes.io/version: 1.5-316
  name: thanos-bucket-cache
  namespace: rhobs-int
