apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: thanos-index-cache-memcached
  name: thanos-index-cache-memcached
  namespace: rhobs-int
stringData:
  thanos.yaml: |
    type: MEMCACHED
    config:
      addresses:
      - dnssrv+_client._tcp.thanos-index-cache.rhobs-int.svc
      timeout: 2s
      max_idle_connections: 2500
      max_async_concurrency: 1000
      max_async_buffer_size: 2500000
      max_get_multi_concurrency: 1000
      max_item_size: 0
      max_get_multi_batch_size: 100000
      dns_provider_update_interval: 10s
      auto_discovery: false
      set_async_circuit_breaker_config:
        enabled: false
        half_open_max_requests: 0
        open_duration: 0s
        min_requests: 0
        consecutive_failures: 0
        failure_percent: 0
    enabled_items: []
    ttl: 0s
type: Opaque
