apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rclone Bucket Sync
  labels:
    app.kubernetes.io/name: rclone-bucket-config-secret
    app.kubernetes.io/part-of: observatorium
description: |
  This template creates a Secret that supports rclone Object Storage config.
parameters:
  - name: NAMESPACE
    description: The namespace where the Secret will be created.
    value: 'observatorium-operations'
  - name: OBJ_STORE_CONFIG_SECRET_NAME
    value: 'rclone-bucket-config'
  - name: SOURCE_ACCESS_KEY_ID
  - name: SOURCE_SECRET_ACCESS_KEY
  - name: SOURCE_S3_BUCKET_PROVIDER
  - name: SOURCE_S3_BUCKET_NAME
  - name: SOURCE_S3_BUCKET_ENDPOINT
  - name: SOURCE_S3_BUCKET_REGION
  - name: TARGET_ACCESS_KEY_ID
  - name: TARGET_SECRET_ACCESS_KEY
  - name: TARGET_S3_BUCKET_PROVIDER
  - name: TARGET_S3_BUCKET_NAME
  - name: TARGET_S3_BUCKET_ENDPOINT
  - name: TARGET_S3_BUCKET_REGION
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${OBJ_STORE_CONFIG_SECRET_NAME}
      namespace: ${NAMESPACE}
      labels:
        app.kubernetes.io/name: rclone-bucket-replicate-secret
        app.kubernetes.io/part-of: observatorium
    type: Opaque
    stringData:
      # Source remote configurations

      RCLONE_CONFIG_SRC_TYPE: "s3"
      RCLONE_CONFIG_SRC_PROVIDER: ${SOURCE_S3_BUCKET_PROVIDER}
      RCLONE_CONFIG_SRC_ENV_AUTH: "false"
      RCLONE_CONFIG_SRC_ENDPOINT: ${SOURCE_S3_BUCKET_ENDPOINT}
      RCLONE_CONFIG_SRC_ACCESS_KEY_ID: ${SOURCE_ACCESS_KEY_ID}
      RCLONE_CONFIG_SRC_SECRET_ACCESS_KEY: ${SOURCE_SECRET_ACCESS_KEY}
      RCLONE_CONFIG_SRC_REGION: ${SOURCE_S3_BUCKET_REGION}

      # Source remote configurations

      RCLONE_CONFIG_DST_TYPE: "s3"
      RCLONE_CONFIG_DST_PROVIDER: ${TARGET_S3_BUCKET_PROVIDER}
      RCLONE_CONFIG_DST_ENV_AUTH: "false"
      RCLONE_CONFIG_DST_ENDPOINT: ${TARGET_S3_BUCKET_ENDPOINT}
      RCLONE_CONFIG_DST_ACCESS_KEY_ID: ${TARGET_ACCESS_KEY_ID}
      RCLONE_CONFIG_DST_SECRET_ACCESS_KEY: ${TARGET_SECRET_ACCESS_KEY}
      RCLONE_CONFIG_DST_REGION: ${TARGET_S3_BUCKET_REGION}


