apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: observatorium-api
objects:
- apiVersion: v1
  data:
    rbac.yaml: |
      roleBindings:
      - name: d4045e4b-7b9c-46fc-8af0-5d483d9d205b
        roles:
        - hcp-metrics-read
        - hcp-metrics-write
        - hcp-logs-read
        - hcp-logs-write
        - hcp-probes-read
        - hcp-probes-write
        subjects:
        - kind: user
          name: service-account-d4045e4b-7b9c-46fc-8af0-5d483d9d205b
      roles:
      - name: hcp-metrics-read
        permissions:
        - read
        resources:
        - metrics
        tenants:
        - hcp
      - name: hcp-metrics-write
        permissions:
        - write
        resources:
        - metrics
        tenants:
        - hcp
      - name: hcp-logs-read
        permissions:
        - read
        resources:
        - logs
        tenants:
        - hcp
      - name: hcp-logs-write
        permissions:
        - write
        resources:
        - logs
        tenants:
        - hcp
      - name: hcp-probes-read
        permissions:
        - read
        resources:
        - probes
        tenants:
        - hcp
      - name: hcp-probes-write
        permissions:
        - write
        resources:
        - probes
        tenants:
        - hcp
  kind: ConfigMap
  metadata:
    annotations:
      qontract.recycle: "true"
    labels:
      app.kubernetes.io/component: api
      app.kubernetes.io/instance: rhobs
      app.kubernetes.io/name: observatorium-api
      app.kubernetes.io/part-of: rhobs
      app.kubernetes.io/version: eace2da37e3111cf894c462d39e50bf85f51f7f8
    name: observatorium-api
    namespace: rhobs-int
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app.kubernetes.io/component: api
      app.kubernetes.io/instance: rhobs
      app.kubernetes.io/name: observatorium-api
      app.kubernetes.io/part-of: rhobs
      app.kubernetes.io/version: eace2da37e3111cf894c462d39e50bf85f51f7f8
    name: observatorium-api
    namespace: rhobs-int
  spec:
    replicas: 2
    selector:
      matchLabels:
        app.kubernetes.io/component: api
        app.kubernetes.io/instance: rhobs
        app.kubernetes.io/name: observatorium-api
        app.kubernetes.io/part-of: rhobs
    strategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        labels:
          app.kubernetes.io/component: api
          app.kubernetes.io/instance: rhobs
          app.kubernetes.io/name: observatorium-api
          app.kubernetes.io/part-of: rhobs
          app.kubernetes.io/version: eace2da37e3111cf894c462d39e50bf85f51f7f8
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - observatorium-api
                topologyKey: kubernetes.io/hostname
              weight: 100
        containers:
        - args:
          - --web.listen=0.0.0.0:8080
          - --web.internal.listen=0.0.0.0:8081
          - --log.level=info
          - --metrics.alertmanager.endpoint=http://alertmanager.rhobs-int.svc.cluster.local:9093
          - --rbac.config=/etc/observatorium/rbac.yaml
          - --tenants.config=/etc/observatorium/tenants.yaml
          - --server.read-timeout=5m
          - --metrics.read.endpoint=http://thanos-query-frontend-rhobs.rhobs-int.svc.cluster.local:9090
          - --metrics.write.endpoint=http://thanos-receive-router-rhobs.rhobs-int.svc.cluster.local:19291
          - --metrics.status.endpoint=http://thanos-query-rhobs.rhobs-int.svc.cluster.local:9090
          - --logs.write-timeout=4m0s
          - --logs.read.endpoint=http://observatorium-lokistack-query-frontend-http.rhobs-int.svc.cluster.local:3100
          - --logs.tail.endpoint=http://observatorium-lokistack-query-frontend-http.rhobs-int.svc.cluster.local:3100
          - --logs.write.endpoint=http://observatorium-lokistack-distributor-http.rhobs-int.svc.cluster.local:3100
          - --probes.endpoint=http://synthetics-api.rhobs-int.svc.cluster.local:8080
          image: quay.io/redhat-services-prod/rhobs-mco-tenant/rhobs-observatorium-api:eace2da37e3111cf894c462d39e50bf85f51f7f8
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /live
              port: 8081
              scheme: HTTP
            periodSeconds: 30
          name: observatorium-api
          ports:
          - containerPort: 8090
            name: grpc-public
          - containerPort: 8081
            name: internal
          - containerPort: 8080
            name: public
          readinessProbe:
            failureThreshold: 12
            httpGet:
              path: /ready
              port: 8081
              scheme: HTTP
            periodSeconds: 5
          resources: {}
          volumeMounts:
          - mountPath: /etc/observatorium/rbac.yaml
            name: rbac
            readOnly: true
            subPath: rbac.yaml
          - mountPath: /etc/observatorium/tenants.yaml
            name: tenants
            readOnly: true
            subPath: tenants.yaml
        serviceAccountName: observatorium-api
        volumes:
        - configMap:
            name: observatorium-api
          name: rbac
        - name: tenants
          secret:
            secretName: observatorium-api
  status: {}
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      qontract.recycle: "true"
    labels:
      app.kubernetes.io/component: api
      app.kubernetes.io/instance: rhobs
      app.kubernetes.io/name: observatorium-api
      app.kubernetes.io/part-of: rhobs
      app.kubernetes.io/version: eace2da37e3111cf894c462d39e50bf85f51f7f8
    name: observatorium-api
    namespace: rhobs-int
  stringData:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    issuer-url: https://sso.redhat.com/auth/realms/redhat-external
    tenants.yaml: |
      tenants:
      - name: hcp
        id: EFD08939-FE1D-41A1-A28A-BE9A9BC68003
        oidc:
          clientID: ${CLIENT_ID}
          clientSecret: ${CLIENT_SECRET}
          issuerURL: https://sso.redhat.com/auth/realms/redhat-external
          redirectURL: https://observatorium-mst.api.stage.openshift.com/oidc/odfms/callback
          usernameClaim: preferred_username
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app.kubernetes.io/component: api
      app.kubernetes.io/instance: rhobs
      app.kubernetes.io/name: observatorium-api
      app.kubernetes.io/part-of: rhobs
      app.kubernetes.io/version: eace2da37e3111cf894c462d39e50bf85f51f7f8
    name: observatorium-api
    namespace: rhobs-int
  spec:
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - appProtocol: h2c
      name: grpc-public
      port: 8090
      protocol: TCP
      targetPort: 8090
    - appProtocol: http
      name: internal
      port: 8081
      protocol: TCP
      targetPort: 8081
    - appProtocol: http
      name: public
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app.kubernetes.io/component: api
      app.kubernetes.io/instance: rhobs
      app.kubernetes.io/name: observatorium-api
      app.kubernetes.io/part-of: rhobs
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app.kubernetes.io/component: api
      app.kubernetes.io/instance: rhobs
      app.kubernetes.io/name: observatorium-api
      app.kubernetes.io/part-of: rhobs
      app.kubernetes.io/version: eace2da37e3111cf894c462d39e50bf85f51f7f8
    name: observatorium-api
    namespace: rhobs-int
parameters:
- description: Organization ID for OSD
  name: OSD_ORGANIZATION_ID
- description: Organization ID for SD Ops
  name: SD_OPS_ORGANIZATION_ID
- description: Organization ID for CNVQE
  name: CNVQE_ORGANIZATION_ID
- description: Client ID for OIDC
  name: CLIENT_ID
- description: Client secret for OIDC
  name: CLIENT_SECRET
