apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: loki-rhobs
objects:
- apiVersion: loki.grafana.com/v1
  kind: LokiStack
  metadata:
    creationTimestamp: null
    name: observatorium-lokistack
    namespace: rhobs-int
  spec:
    limits:
      global:
        ingestion:
          ingestionBurstSize: 16
          ingestionRate: 4
        queries:
          queryTimeout: 5m
    managementState: Managed
    size: ${LOKI_SIZE}
    storage:
      schemas:
      - effectiveDate: "2025-06-06"
        version: v13
      secret:
        name: ${LOKI_STORAGE_SECRET_NAME}
        type: s3
    storageClassName: ${LOKI_STORAGE_CLASS}
    template:
      distributor:
        replicas: 2
      ingester:
        replicas: 2
      querier:
        replicas: 2
      queryFrontend:
        replicas: 2
  status:
    components: {}
    storage: {}
parameters:
- name: LOKI_SIZE
  value: 1x.medium
- name: LOKI_STORAGE_SECRET_NAME
  value: loki-default-bucket
- name: LOKI_STORAGE_CLASS
  value: gp3-csi
