apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: loki-rhobs
objects:
- apiVersion: loki.grafana.com/v1
  kind: LokiStack
  metadata:
    name: observatorium-lokistack
    namespace: rhobs-int
  spec:
    limits:
      global:
        ingestion:
          ingestionBurstSize: 256
          ingestionRate: 20
          maxLineSize: 262144
        otlp:
          streamLabels:
            resourceAttributes:
            - name: k8s.namespace.name
            - name: openshift.label.cluster_name
            - name: openshift.log.source
            - name: openshift.log.type
        queries:
          queryTimeout: 5m
    managementState: Managed
    size: ${LOKI_SIZE}
    storage:
      schemas:
      - effectiveDate: "2025-06-06"
        version: v13
      secret:
        name: ${LOKI_STORAGE_SECRET_NAME}
        type: s3
    storageClassName: ${LOKI_STORAGE_CLASS}
    template:
      distributor:
        replicas: 3
      ingester:
        replicas: 6
      querier:
        replicas: 2
      queryFrontend:
        replicas: 2
  status:
    components: {}
    storage: {}
parameters:
- name: LOKI_SIZE
  value: 1x.medium
- name: LOKI_STORAGE_SECRET_NAME
  value: loki-default-bucket
- name: LOKI_STORAGE_CLASS
  value: gp3-csi
