apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: rhobs
    app.kubernetes.io/name: rhobs-gateway
    app.kubernetes.io/part-of: rhobs
    app.kubernetes.io/version: 9fc0a6990fbc9cdcd81a69fc97aba8c3ccd66f8c
  name: rhobs-gateway
  namespace: rhobs-int
