apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: rhobs
    app.kubernetes.io/name: rhobs-gateway
    app.kubernetes.io/part-of: rhobs
    app.kubernetes.io/version: 1fb4dafb58f6158c832f307d8e37729f390f4f5a
  name: rhobs-gateway
  namespace: rhobs-int
