apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/created-by: thanos-operator
    app.kubernetes.io/instance: controller-manager-metrics
    app.kubernetes.io/managed-by: rhobs
    app.kubernetes.io/name: servicemonitor
    app.kubernetes.io/part-of: thanos-operator
    prometheus: app-sre
  name: thanos-operator-controller-manager-metrics
  namespace: openshift-customer-monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    port: https
    scheme: https
    tlsConfig:
      ca: {}
      cert: {}
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - rhobs-stage
  selector:
    matchLabels:
      control-plane: controller-manager
