apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: memcached
    app.kubernetes.io/instance: rhobs
    app.kubernetes.io/name: thanos-index-cache
    app.kubernetes.io/part-of: rhobs
    prometheus: app-sre
  name: thanos-index-cache
  namespace: openshift-customer-monitoring
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    port: metrics
  namespaceSelector:
    matchNames:
    - rhobs-stage
  selector:
    matchLabels:
      app.kubernetes.io/component: memcached
      app.kubernetes.io/instance: rhobs
      app.kubernetes.io/name: thanos-index-cache
      app.kubernetes.io/part-of: rhobs
