apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhobs-sc-acm-manifestwork-rules
  annotations:
    description: "Template for deploying SC ACM ManifestWork alerting rules to RHOBS"
parameters:
  - name: NAMESPACE
    description: Namespace to deploy the rules to
    required: true
  - name: TENANT
    description: Tenant to deploy the rules to
    required: true
objects:
  - apiVersion: monitoring.coreos.com/v1
    kind: PrometheusRule
    metadata:
      name: sre-acm-manifestwork-alerts
      namespace: ${NAMESPACE}
      labels:
        operator.thanos.io/prometheus-rule: "true"
        operator.thanos.io/tenant: ${TENANT}
    spec:
      groups:
        - name: sre-acm-manifestwork-alerts
          interval: 1m
          rules:
            - alert: ACMManifestWorkAppliedHighFailureRate
              annotations:
                description: "{{ $value | humanizePercentage }} of ManifestWorks are failing to apply, indicating a widespread issue affecting ACM operations."
                runbook_url: "https://github.com/openshift/ops-sop/blob/master/hypershift/alerts/acm/ACMManifestWorkAppliedHighFailureRate.md"
                summary: "High ManifestWork failure rate: {{ $value | humanizePercentage }}"
              expr: |
                sre_acm_manifestwork_applied_failed_ratio > 0.10
              for: 5m
              labels:
                severity: warning
                otel_collect: "true"
