apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhobs-sc-observability-rules
  annotations:
    description: "Template for deploying SC observability health rules to RHOBS"
parameters:
  - name: NAMESPACE
    description: Namespace to deploy the rules to
    required: true
  - name: TENANT
    description: Tenant to deploy the rules to
    required: true
objects:
  - apiVersion: monitoring.coreos.com/v1
    kind: PrometheusRule
    metadata:
      name: sc-watchdog
      namespace: ${NAMESPACE}
      labels:
        operator.thanos.io/prometheus-rule: "true"
        operator.thanos.io/tenant: ${TENANT}
    spec:
      groups:
        - name: sc-watchdog
          interval: 60s
          rules:
            - record: watchdog
              expr: group by (_id)(kube_node_labels)
            - alert: SCWatchdog
              annotations:
                description: >
                  Always-firing watchdog alert for the SC alerting pipeline.
                  If this alert stops firing, the pipeline is broken.
              expr: watchdog
              labels:
                severity: none
