apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: synthetics-api
    app.kubernetes.io/instance: rhobs
    app.kubernetes.io/name: synthetics-api
    app.kubernetes.io/part-of: rhobs
    app.kubernetes.io/version: cea7d4656cd0ad338e580cc6ba266264a9938e5c
  name: synthetics-api
  namespace: rhobs-stage
spec:
  ports:
  - name: synthetics-api
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/component: synthetics-api
    app.kubernetes.io/instance: rhobs
    app.kubernetes.io/name: synthetics-api
    app.kubernetes.io/part-of: rhobs
    app.kubernetes.io/version: cea7d4656cd0ad338e580cc6ba266264a9938e5c
  type: ClusterIP
status:
  loadBalancer: {}
