apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: thanos-operator
    app.kubernetes.io/instance: metrics-reader
    app.kubernetes.io/managed-by: rhobs
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: thanos-operator
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: thanos-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
