apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: thanos-query-range-cache-memcached
  name: thanos-query-range-cache-memcached
  namespace: rhobs-stage
stringData:
  thanos.yaml: |
    type: MEMCACHED
    config:
      addresses:
      - dnssrv+_client._tcp.thanos-query-range-cache.rhobs-stage.svc
      timeout: 5s
      max_idle_connections: 500
      max_async_concurrency: 100
      max_async_buffer_size: 1000000
      max_get_multi_concurrency: 100
      max_item_size: 0
      max_get_multi_batch_size: 500
      dns_provider_update_interval: 30s
      auto_discovery: false
      set_async_circuit_breaker_config:
        enabled: false
        half_open_max_requests: 0
        open_duration: 0s
        min_requests: 0
        consecutive_failures: 0
        failure_percent: 0
      expiration: 0s
type: Opaque
