apiVersion: monitoring.thanos.io/v1alpha1
kind: ThanosQuery
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: query-frontend-tls
    serviceaccounts.openshift.io/oauth-redirectreference.application: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"thanos-query-frontend-rhobs"}}'
  name: rhobs
  namespace: rhobs-stage
spec:
  baseImage: quay.io/redhat-services-prod/rhobs-mco-tenant/rhobs-thanos
  customStoreLabelSelector:
    matchLabels:
      app.kubernetes.io/part-of: thanos
      operator.thanos.io/store-api: "true"
  grpcProxyStrategy: lazy
  imagePullPolicy: IfNotPresent
  logFormat: logfmt
  logLevel: info
  podDisruptionBudgetConfig:
    enable: false
  queryFrontend:
    additionalContainers:
    - args:
      - -provider=openshift
      - -https-address=:8443
      - -http-address=
      - -email-domain=*
      - -upstream=http://localhost:9090
      - -openshift-service-account=thanos-query-frontend-rhobs
      - '-openshift-sar={"resource": "namespaces", "verb": "get", "name": "rhobs-stage",
        "namespace": "rhobs-stage"}'
      - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get",
        "name": "rhobs-stage", "namespace": "rhobs-stage"}}'
      - -tls-cert=/etc/tls/private/tls.crt
      - -tls-key=/etc/tls/private/tls.key
      - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
      - -cookie-secret-file=/etc/oauth-cookie/cookie.txt
      - -openshift-ca=/etc/pki/tls/cert.pem
      - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      image: registry.redhat.io/openshift4/ose-oauth-proxy:v4.14
      name: oauth-proxy
      ports:
      - containerPort: 8443
        name: https
        protocol: TCP
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationMessagePolicy: FallbackToLogsOnError
      volumeMounts:
      - mountPath: /etc/tls/private
        name: tls
        readOnly: true
      - mountPath: /etc/oauth-cookie
        name: oauth-cookie
        readOnly: true
    additionalServicePorts:
    - name: https
      port: 8443
      targetPort: 8443
    additionalVolumes:
    - name: tls
      secret:
        secretName: query-frontend-tls
    - name: oauth-cookie
      secret:
        secretName: oauth-cookie
    baseImage: quay.io/redhat-services-prod/rhobs-mco-tenant/rhobs-thanos
    compressResponses: true
    imagePullPolicy: IfNotPresent
    labelsDefaultTimeRange: 336h
    labelsMaxRetries: 3
    labelsSplitInterval: 48h
    logFormat: logfmt
    logLevel: info
    logQueriesLongerThan: 10s
    queryLabelSelector:
      matchLabels:
        operator.thanos.io/query-api: "true"
    queryRangeMaxRetries: 3
    queryRangeResponseCacheConfig:
      externalCacheConfig:
        key: thanos.yaml
        name: thanos-query-range-cache-memcached
    queryRangeSplitInterval: 48h
    replicas: 1
    resourceRequirements:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    securityContext:
      seccompProfile:
        type: RuntimeDefault
    version: 0dcacf2a5108328d537dbcf59fcabc9b69f08a2b
  replicaLabels:
  - prometheus_replica
  - replica
  - rule_replica
  replicas: 1
  resourceRequirements:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  telemetryQuantiles:
    duration:
    - "0.1"
    - "0.25"
    - "0.75"
    - "1.25"
    - "1.75"
    - "2.5"
    - "3"
    - "5"
    - "10"
    - "15"
    - "30"
    - "60"
    - "120"
  version: 0dcacf2a5108328d537dbcf59fcabc9b69f08a2b
  webConfig:
    prefixHeader: X-Forwarded-Prefix
status:
  querierStatus:
    availableReplicas: 0
    readyReplicas: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
  queryFrontendStatus:
    availableReplicas: 0
    readyReplicas: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
