apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhobs-logging-cluster-log-forwarder
  annotations:
    description: "Template for deploying CLF for HCP to support log forwarding to RHOBS"
parameters:
  - name: REGION
    description: region of SC/MC clusters
    required: true
  - name: SECTOR
    description: sector of SC/MC clusters
    required: true

objects:
- apiVersion: hive.openshift.io/v1
  kind: SelectorSyncSet
  metadata:
    labels:
      managed.openshift.io/osd: 'true'
    name: rhobs-logs-cluster-log-forwarder
  spec:
    resourceApplyMode: Sync
    enableResourceTemplates: true
    clusterDeploymentSelector:
      matchLabels:
        api.openshift.com/managed: 'true'
      matchExpressions:
        - key: api.openshift.com/fedramp
          operator: NotIn
          values:
            - 'true'
        - key: ext-hypershift.openshift.io/cluster-type
          operator: In
          values:
            - management-cluster
            - service-cluster
        - key: ext-hypershift.openshift.io/cluster-region
          operator: In
          values:
            - ${REGION}
        - key: ext-hypershift.openshift.io/cluster-sector
          operator: In
          values:
            - ${SECTOR}


    resources:
      - apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: rhobs-logs
          namespace: openshift-logging
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: rhobs-logs-collect-application-logs
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: collect-application-logs
        subjects:
        - kind: ServiceAccount
          name: rhobs-logs
          namespace: openshift-logging
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: rhobs-logs-collect-infrastructure-logs
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: collect-infrastructure-logs
        subjects:
        - kind: ServiceAccount
          name: rhobs-logs
          namespace: openshift-logging
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: rhobs-logs-collect-audit-logs
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: collect-audit-logs
        subjects:
        - kind: ServiceAccount
          name: rhobs-logs
          namespace: openshift-logging
      - apiVersion: observability.openshift.io/v1
        kind: ClusterLogForwarder
        metadata:
          name: rhobs
          namespace: openshift-logging
          annotations:
            observability.openshift.io/tech-preview-otlp-output: "enabled"
        spec:
          serviceAccount:
            name: rhobs-logs
          filters:
            - name: cluster-id-filter
              openshiftLabels:
                cluster_id: "{{ fromCDLabel \"api.openshift.com/name\" }}"
              type: openshiftLabels
          pipelines:
            - filterRefs:
                - cluster-id-filter
              name: logging-to-loki
              inputRefs:
                - application
                - infrastructure
              outputRefs:
                - loki-remote
          outputs:
            - name: loki-remote
              type: otlp
              otlp:
                url: http://token-refresher.openshift-logging.svc:80/api/logs/v1/hcp/otlp/v1/logs
