apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhobs-logging-token-refresher
  annotations:
    description: "Template for deploying token refresher for HCP to support log forwarding"
parameters:
  - name: REGION
    description: region of SC/MC clusters
  - name: SECTOR
    description: sector of SC/MC clusters
    required: true
  - name: CLIENT_ID
    description: "OIDC client ID"
    required: true
  - name: CLIENT_SECRET
    description: "OIDC client secret"
    required: true
  - name: LOGS_WRITE_URL
    description: "URL for logs write endpoint"
    required: true
  - name: ADDITIONAL_MATCH_EXPRESSION
    description: Hive SelectorSyncSet matchExpressions override. By default this template will target all MC's and SC's discovered.

objects:
- apiVersion: hive.openshift.io/v1
  kind: SelectorSyncSet
  metadata:
    labels:
      managed.openshift.io/osd: 'true'
    name: rhobs-logs-token-refresher
  spec:
    resourceApplyMode: Sync
    clusterDeploymentSelector:
      matchLabels:
        api.openshift.com/managed: 'true'
      matchExpressions:
        - key: api.openshift.com/fedramp
          operator: NotIn
          values:
            - 'true'

        - key: ext-hypershift.openshift.io/cluster-type
          operator: In
          values:
            - management-cluster
            - service-cluster

        ${ADDITIONAL_MATCH_EXPRESSION}

    resources:
      - apiVersion: v1
        kind: Secret
        metadata:
          name: observatorium-credentials
          namespace: openshift-logging
        type: Opaque
        stringData:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}

      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          labels:
            app.kubernetes.io/component: authentication-proxy
            app.kubernetes.io/name: token-refresher
          name: rhobs-logs-token-refresher
          namespace: openshift-logging
        spec:
          replicas: 2
          selector:
            matchLabels:
              app.kubernetes.io/component: authentication-proxy
              app.kubernetes.io/name: token-refresher
          template:
            metadata:
              labels:
                app.kubernetes.io/component: authentication-proxy
                app.kubernetes.io/name: token-refresher
            spec:
              affinity:
                nodeAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                    - preference:
                        matchExpressions:
                          - key: node-role.kubernetes.io/infra
                            operator: Exists
                      weight: 1
              tolerations:
                - effect: NoSchedule
                  key: node-role.kubernetes.io/infra
                  operator: Exists
              volumes:
                - configMap:
                    defaultMode: 420
                    items:
                      - key: ca-bundle.crt
                        path: ca-certificates.crt
                    name: token-refresher-trusted-ca-bundle
                  name: token-refresher-trusted-ca-bundle
              containers:
                - args:
                    - --log.level=info
                    - --log.format=logfmt
                    - --web.listen=0.0.0.0:8080
                    - --web.internal.listen=0.0.0.0:8081
                    - --oidc.client-id=$(OIDC_CLIENT_ID)
                    - --oidc.client-secret=$(OIDC_CLIENT_SECRET)
                    - --oidc.issuer-url=https://sso.redhat.com/auth/realms/redhat-external
                    - --upstream.url=${LOGS_WRITE_URL}
                    - --scope=profile
                  env:
                    - name: OIDC_CLIENT_ID
                      valueFrom:
                        secretKeyRef:
                          name: observatorium-credentials
                          key: client-id
                    - name: OIDC_CLIENT_SECRET
                      valueFrom:
                        secretKeyRef:
                          name: observatorium-credentials
                          key: client-secret
                  image: quay.io/observatorium/token-refresher@sha256:0a3562d2a10bbb68f3edf60b3e471a1cb344735673dde2af16776b53c6674a43
                  name: token-refresher
                  ports:
                    - containerPort: 8080
                      name: http
                  volumeMounts:
                    - mountPath: /etc/ssl/certs/
                      name: token-refresher-trusted-ca-bundle
                      readOnly: true

      - apiVersion: v1
        kind: Service
        metadata:
          labels:
            app.kubernetes.io/component: authentication-proxy
            app.kubernetes.io/name: token-refresher
          name: token-refresher
          namespace: openshift-logging
        spec:
          ports:
            - name: http
              port: 80
              targetPort: 8080
          selector:
            app.kubernetes.io/component: authentication-proxy
            app.kubernetes.io/name: token-refresher

      - apiVersion: v1
        kind: ConfigMap
        metadata:
          namespace: openshift-logging
          name: token-refresher-trusted-ca-bundle
          labels:
            config.openshift.io/inject-trusted-cabundle: 'true'
