{
 "title": "Thanos / Receive / Overview",
 "tags": [
  "thanos",
  "receive"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "router_job",
    "label": "router_job",
    "query": {
     "query": "label_values(thanos_build_info{job=~\".*thanos-receive-router.*\"}, job)"
    }
   },
   {
    "name": "ingester_job",
    "label": "ingester_job",
    "query": {
     "query": "label_values(thanos_build_info{job=~\".*thanos-receive-ingester.*\"}, job)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(thanos_status{}, namespace)"
    }
   },
   {
    "name": "tenant",
    "label": "tenant",
    "query": {
     "query": "label_values(prometheus_tsdb_head_max_time{job=~\"$ingester_job\",namespace=\"$namespace\"}, tenant)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Remote Write v1 - Incoming Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Remote Write Rate",
   "type": "timeseries",
   "description": "Shows rate of incoming Remote Write v1 requests.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, handler, code) (\n  rate(http_requests_total{handler=\"receive\",job=~\"$router_job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}} {{namespace}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Remote Write Errors",
   "type": "timeseries",
   "description": "Shows percentage of errors for incoming Remote Write v1 requests.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum by (namespace, job, code) (\n      rate(\n        http_requests_total{code=~\"5..\",handler=\"receive\",job=~\"$router_job\",namespace=\"$namespace\"}[$__rate_interval]\n      )\n    )\n  / ignoring (code) group_left ()\n    sum by (namespace, job) (\n      rate(http_requests_total{handler=\"receive\",job=~\"$router_job\",namespace=\"$namespace\"}[$__rate_interval])\n    )\n)\n*\n  100",
     "legendFormat": "{{job}} {{namespace}} {{code}} {{handler}}"
    }
   ]
  },
  {
   "title": "Remote Write Duration",
   "type": "timeseries",
   "description": "Duration percentiles of successful Remote Write requests.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, le) (\n    rate(\n      http_request_duration_seconds_bucket{handler=\"receive\",job=~\"$router_job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p50 {{job}} - {{namespace}} duration"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, le) (\n    rate(\n      http_request_duration_seconds_bucket{handler=\"receive\",job=~\"$router_job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p90 {{job}} - {{namespace}} duration"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, le) (\n    rate(\n      http_request_duration_seconds_bucket{handler=\"receive\",job=~\"$router_job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p99 {{job}} {{namespace}} duration"
    }
   ]
  },
  {
   "title": "Remote Write v1 - Incoming Requests (tenanted)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Remote Write Rate by tenant",
   "type": "timeseries",
   "description": "Shows rate of incoming Remote Write v1 requests split by tenant.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (tenant, job, handler, code) (\n  rate(\n    http_requests_total{handler=\"receive\",job=~\"$router_job\",namespace=\"$namespace\",tenant=~\"$tenant\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "{{tenant}} {{code}} {{job}} {{namespace}} {{handler}}"
    }
   ]
  },
  {
   "title": "Remote Write Errors by tenant",
   "type": "timeseries",
   "description": "Shows percentage of errors for incoming Remote Write v1 requests split by tenant.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum by (tenant, namespace, job, code) (\n      rate(\n        http_requests_total{code!~\"2..\",handler=\"receive\",job=~\"$router_job\",namespace=\"$namespace\",tenant=~\"$tenant\"}[$__rate_interval]\n      )\n    )\n  / ignoring (code) group_left ()\n    sum by (tenant, namespace, job) (\n      rate(\n        http_requests_total{handler=\"receive\",job=~\"$router_job\",namespace=\"$namespace\",tenant=~\"$tenant\"}[$__rate_interval]\n      )\n    )\n)\n*\n  100",
     "legendFormat": "{{tenant}} {{code}} {{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Average Remote Write Duration by tenant",
   "type": "timeseries",
   "description": "Average duration of Remote Write requests by tenants.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "  sum by (namespace, job, tenant) (\n    rate(\n      http_request_duration_seconds_sum{handler=\"receive\",job=~\"$router_job\",namespace=\"$namespace\",tenant=~\"$tenant\"}[$__rate_interval]\n    )\n  )\n/\n  sum by (namespace, job, tenant) (\n    http_request_duration_seconds_count{handler=\"receive\",job=~\"$router_job\",namespace=\"$namespace\",tenant=~\"$tenant\"}\n  )",
     "legendFormat": "{{tenant}} {{namespace}} {{job}}"
    }
   ]
  },
  {
   "title": "Remote Write v1 - HTTP Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "Average Successful Remote Write request size",
   "type": "timeseries",
   "description": "Shows average size of successful remote write request.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "  sum by (namespace, job, tenant) (\n    rate(\n      http_request_size_bytes_sum{code=~\"2..\",handler=\"receive\",job=~\"$router_job\",namespace=\"$namespace\",tenant=~\"$tenant\"}[$__rate_interval]\n    )\n  )\n/\n  sum by (namespace, job, tenant) (\n    rate(\n      http_request_size_bytes_count{code=~\"2..\",handler=\"receive\",job=~\"$router_job\",namespace=\"$namespace\",tenant=~\"$tenant\"}[$__rate_interval]\n    )\n  )",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Average Failed Remote Write request size",
   "type": "timeseries",
   "description": "Shows average size of failed remote write request.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "  sum by (namespace, job, tenant) (\n    rate(\n      http_request_size_bytes_sum{code!~\"2..\",handler=\"receive\",job=~\"$router_job\",namespace=\"$namespace\",tenant=~\"$tenant\"}[$__rate_interval]\n    )\n  )\n/\n  sum by (namespace, job, tenant) (\n    rate(\n      http_request_size_bytes_count{code!~\"2..\",handler=\"receive\",job=~\"$router_job\",namespace=\"$namespace\",tenant=~\"$tenant\"}[$__rate_interval]\n    )\n  )",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Inflight remote write requests",
   "type": "timeseries",
   "description": "Shows inflight remote write HTTP requests.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, tenant, method) (\n  http_inflight_requests{handler=\"receive\",job=~\"$router_job\",namespace=\"$namespace\", tenant=\"$tenant\"}\n)",
     "legendFormat": "{{method}} {{tenant}}"
    }
   ]
  },
  { "title": "Series and Samples (tenanted)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Rate of Series ingested",
   "type": "timeseries",
   "description": "Shows rate of timeseries ingested by Receive, split by tenant.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, tenant) (\n  rate(\n    thanos_receive_write_timeseries_sum{code=~\"2..\",job=~\"$router_job\",namespace=\"$namespace\",tenant=~\"$tenant\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Rate of Series not ingested",
   "type": "timeseries",
   "description": "Shows rate of timeseries not ingested by Receive, split by tenant.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, tenant) (\n  rate(\n    thanos_receive_write_timeseries_sum{code!~\"2..\",job=~\"$router_job\",namespace=\"$namespace\",tenant=~\"$tenant\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Rate of Samples ingested",
   "type": "timeseries",
   "description": "Shows rate of samples ingested by Receive, split by tenant.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, tenant) (\n  rate(\n    thanos_receive_write_samples_sum{code=~\"2..\",job=~\"$router_job\",namespace=\"$namespace\",tenant=~\"$tenant\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Rate of Samples not ingested",
   "type": "timeseries",
   "description": "Shows rate of samples not ingested by Receive, split by tenant.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, tenant) (\n  rate(\n    thanos_receive_write_samples_sum{code!~\"2..\",job=~\"$router_job\",namespace=\"$namespace\",tenant=~\"$tenant\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  { "title": "Remote Write Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Rate of replication requests",
   "type": "timeseries",
   "description": "Shows rate of replication requests between Receives.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job) (\n  rate(thanos_receive_replications_total{job=~\"$router_job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Rate of replication errors",
   "type": "timeseries",
   "description": "Shows rate of replication errors between Receives.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job) (\n  rate(\n    thanos_receive_replications_total{job=~\"$router_job\",namespace=\"$namespace\",result=\"error\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Remote Write Forward", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Rate of forward requests",
   "type": "timeseries",
   "description": "Shows rate of forward requests between Receives.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job) (\n  rate(thanos_receive_forward_requests_total{job=~\"$router_job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Rate of forward errors",
   "type": "timeseries",
   "description": "Shows rate of forward errors between Receives.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job) (\n  rate(\n    thanos_receive_forward_requests_total{job=~\"$router_job\",namespace=\"$namespace\",result=\"error\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Write gRPC Unary (WritableStore)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 }
  },
  {
   "title": "Unary gRPC Write request rate",
   "type": "timeseries",
   "description": "Shows rate of handled Unary gRPC Write requests (WritableStore).",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, grpc_method, grpc_code) (\n  rate(\n    grpc_server_handled_total{grpc_method=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$ingester_job\",namespace=\"$namespace\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "{{namespace}} {{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Unary gRPC Write error rate",
   "type": "timeseries",
   "description": "Shows percentage of errors of Unary gRPC Write requests (WritableStore).",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "  sum by (namespace, job, grpc_code) (\n    rate(\n      grpc_server_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",grpc_method=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$ingester_job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n/ ignoring (grpc_code) group_left ()\n  sum by (namespace, job) (\n    rate(\n      grpc_server_handled_total{grpc_method=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$ingester_job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )",
     "legendFormat": "{{namespace}} {{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Unary gRPC Write duration",
   "type": "timeseries",
   "description": "Shows duration percentiles of handled Unary gRPC Write requests (WritableStore).",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_method=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$ingester_job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p50 {{namespace}} {{job}}"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_method=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$ingester_job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p90 {{namespace}} {{job}}"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_method=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$ingester_job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p99 {{namespace}} {{job}}"
    }
   ]
  },
  {
   "title": "Read gRPC Unary (StoreAPI Info/Labels)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 }
  },
  {
   "title": "Unary gRPC Read request rate",
   "type": "timeseries",
   "description": "Shows rate of handled Unary gRPC Read requests (StoreAPI).",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, grpc_method, grpc_code) (\n  rate(\n    grpc_server_handled_total{grpc_method!=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$ingester_job\",namespace=\"$namespace\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "{{namespace}} {{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Unary gRPC Read error rate",
   "type": "timeseries",
   "description": "Shows percentage of errors of Unary gRPC Read requests (StoreAPI).",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "  sum by (namespace, job, grpc_code) (\n    rate(\n      grpc_server_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",grpc_method!=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$ingester_job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n/ ignoring (grpc_code) group_left ()\n  sum by (namespace, job) (\n    rate(\n      grpc_server_handled_total{grpc_method!=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$ingester_job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )",
     "legendFormat": "{{namespace}} {{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Unary gRPC Read duration",
   "type": "timeseries",
   "description": "Shows duration percentiles of handled Unary gRPC Read requests (StoreAPI).",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_method!=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$ingester_job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p50 {{namespace}} {{job}}"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_method!=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$ingester_job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p90 {{namespace}} {{job}}"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_method!=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$ingester_job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p99 {{namespace}} {{job}}"
    }
   ]
  },
  {
   "title": "Read gRPC Stream (StoreAPI Series/Exemplars)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 }
  },
  {
   "title": "Stream gRPC Read request rate",
   "type": "timeseries",
   "description": "Shows rate of handled Stream gRPC Read requests (StoreAPI Series/Exemplar calls).",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, grpc_method, grpc_code) (\n  rate(\n    grpc_server_handled_total{grpc_type=\"server_stream\",job=~\"$ingester_job\",namespace=\"$namespace\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "{{namespace}} {{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Stream gRPC Read error rate",
   "type": "timeseries",
   "description": "Shows percentage of errors of Stream gRPC Read requests (StoreAPI Series/Exemplar calls).",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "  sum by (namespace, job, grpc_code) (\n    rate(\n      grpc_server_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",grpc_type=\"server_stream\",job=~\"$ingester_job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n/ ignoring (grpc_code) group_left ()\n  sum by (namespace, job) (\n    rate(\n      grpc_server_handled_total{grpc_type=\"server_stream\",job=~\"$ingester_job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )",
     "legendFormat": "{{namespace}} {{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Stream gRPC Read duration",
   "type": "timeseries",
   "description": "Shows duration percentiles of handled Stream gRPC Read requests (StoreAPI Series/Exemplar calls).",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_type=\"server_stream\",job=~\"$ingester_job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p50 {{namespace}} {{job}}"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_type=\"server_stream\",job=~\"$ingester_job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p90 {{namespace}} {{job}}"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_type=\"server_stream\",job=~\"$ingester_job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p99 {{namespace}} {{job}}"
    }
   ]
  },
  { "title": "Last Bucket Upload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Time Since Last Block Upload",
   "type": "stat",
   "description": "Shows the time since the last successful block upload for each Receive ingester. Green indicates recent uploads, yellow indicates uploads older than 30 minutes, and red indicates uploads older than 2 hours.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  time()\n-\n  max by (namespace, job, bucket) (\n    thanos_objstore_bucket_last_successful_upload_time{job=~\"$ingester_job\",namespace=\"$namespace\"}\n  )",
     "legendFormat": "{{job}} - {{bucket}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Appended Samples",
   "type": "timeseries",
   "description": "Shows rate of samples appended to Receive TSDB across all tenants.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, job) (\n  rate(prometheus_tsdb_head_samples_appended_total{job=~\"$ingester_job\",namespace=~\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}} - {{namespace}}"
    }
   ]
  },
  {
   "title": "Head Series",
   "type": "timeseries",
   "description": "Shows number of series in Receive TSDB head across all tenants.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, job) (prometheus_tsdb_head_series{job=~\"$ingester_job\",namespace=~\"$namespace\"})",
     "legendFormat": "{{job}} - {{namespace}} - Head Series"
    }
   ]
  },
  {
   "title": "Head Chunks",
   "type": "timeseries",
   "description": "Shows number of chunks in Prometheus TSDB head across all tenants.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, job) (prometheus_tsdb_head_chunks{job=~\"$ingester_job\",namespace=~\"$namespace\"})",
     "legendFormat": "{{job}} - {{namespace}} - Head Chunks"
    }
   ]
  },
  { "title": "Resources (Router)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Shows the CPU usage of the router.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$router_job\",namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Shows various memory usage metrics of the router.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=~\"$router_job\",namespace=\"$namespace\"}",
     "legendFormat": "Alloc All {{pod}}"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{job=~\"$router_job\",namespace=\"$namespace\"}",
     "legendFormat": "Alloc Heap {{pod}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"$router_job\",namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Alloc Rate All {{pod}}"
    },
    {
     "expr": "rate(go_memstats_heap_alloc_bytes{job=~\"$router_job\",namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Alloc Rate Heap {{pod}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~\"$router_job\",namespace=\"$namespace\"}",
     "legendFormat": "Inuse Stack {{pod}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"$router_job\",namespace=\"$namespace\"}",
     "legendFormat": "Inuse Heap {{pod}}"
    },
    {
     "expr": "process_resident_memory_bytes{job=~\"$router_job\",namespace=\"$namespace\"}",
     "legendFormat": "Resident Memory {{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Shows the number of goroutines being used by the router.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"$router_job\",namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "description": "Shows the Go garbage collection pause durations for the router.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=~\"$router_job\",namespace=\"$namespace\"}",
     "legendFormat": "{{quantile}} - {{pod}}"
    }
   ]
  },
  { "title": "Resources (Ingester)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Shows the CPU usage of the ingester.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$ingester_job\",namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Shows various memory usage metrics of the ingester.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=~\"$ingester_job\",namespace=\"$namespace\"}",
     "legendFormat": "Alloc All {{pod}}"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{job=~\"$ingester_job\",namespace=\"$namespace\"}",
     "legendFormat": "Alloc Heap {{pod}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"$ingester_job\",namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Alloc Rate All {{pod}}"
    },
    {
     "expr": "rate(go_memstats_heap_alloc_bytes{job=~\"$ingester_job\",namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Alloc Rate Heap {{pod}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~\"$ingester_job\",namespace=\"$namespace\"}",
     "legendFormat": "Inuse Stack {{pod}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"$ingester_job\",namespace=\"$namespace\"}",
     "legendFormat": "Inuse Heap {{pod}}"
    },
    {
     "expr": "process_resident_memory_bytes{job=~\"$ingester_job\",namespace=\"$namespace\"}",
     "legendFormat": "Resident Memory {{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Shows the number of goroutines being used by the ingester.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"$ingester_job\",namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "description": "Shows the Go garbage collection pause durations for the ingester.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=~\"$ingester_job\",namespace=\"$namespace\"}",
     "legendFormat": "{{quantile}} - {{pod}}"
    }
   ]
  }
 ]
}