{
 "title": "Thanos / Query / Overview",
 "tags": [
  "thanos",
  "query"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(thanos_status{}, namespace)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(thanos_build_info{container=\"thanos-query\"}, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Instant Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instant Query Rate",
   "type": "timeseries",
   "description": "Shows rate of incoming instant query (/query) requests.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, handler, code) (\n  rate(http_requests_total{handler=\"query\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}} {{namespace}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Instant Query Errors",
   "type": "timeseries",
   "description": "Shows percentage of errors for incoming instant query (/query) requests.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum by (namespace, job, code) (\n      rate(http_requests_total{code=~\"5..\",handler=\"query\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n    )\n  / ignoring (code) group_left ()\n    sum by (namespace, job) (\n      rate(http_requests_total{handler=\"query\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n    )\n)\n*\n  100",
     "legendFormat": "{{job}} {{namespace}} {{code}} {{handler}}"
    }
   ]
  },
  {
   "title": "Instant Query Duration",
   "type": "timeseries",
   "description": "Duration percentiles of successful instant query (/query) requests.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, le) (\n    rate(\n      http_request_duration_seconds_bucket{handler=\"query\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p50 {{job}} - {{namespace}} duration"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, le) (\n    rate(\n      http_request_duration_seconds_bucket{handler=\"query\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p90 {{job}} - {{namespace}} duration"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, le) (\n    rate(\n      http_request_duration_seconds_bucket{handler=\"query\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p99 {{job}} {{namespace}} duration"
    }
   ]
  },
  { "title": "Range Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Range Query Rate",
   "type": "timeseries",
   "description": "Shows rate of incoming range query (/query_range) requests.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, handler, code) (\n  rate(http_requests_total{handler=\"query_range\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}} {{namespace}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Range Query Errors",
   "type": "timeseries",
   "description": "Shows percentage of errors for incoming range query (/query_range) requests.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum by (namespace, job, code) (\n      rate(\n        http_requests_total{code=~\"5..\",handler=\"query_range\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n      )\n    )\n  / ignoring (code) group_left ()\n    sum by (namespace, job) (\n      rate(http_requests_total{handler=\"query_range\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n    )\n)\n*\n  100",
     "legendFormat": "{{job}} {{namespace}} {{code}} {{handler}}"
    }
   ]
  },
  {
   "title": "Range Query Duration",
   "type": "timeseries",
   "description": "Duration percentiles of successful range query (/query_range) requests.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, le) (\n    rate(\n      http_request_duration_seconds_bucket{handler=\"query_range\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p50 {{job}} - {{namespace}} duration"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, le) (\n    rate(\n      http_request_duration_seconds_bucket{handler=\"query_range\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p90 {{job}} - {{namespace}} duration"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, le) (\n    rate(\n      http_request_duration_seconds_bucket{handler=\"query_range\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p99 {{job}} {{namespace}} duration"
    }
   ]
  },
  {
   "title": "Read gRPC Unary (StoreAPI Info/Labels)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "Unary gRPC Read request rate",
   "type": "timeseries",
   "description": "Shows rate of handled Unary gRPC Read requests (StoreAPI).",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, grpc_method, grpc_code) (\n  rate(\n    grpc_server_handled_total{grpc_method!=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "{{namespace}} {{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Unary gRPC Read error rate",
   "type": "timeseries",
   "description": "Shows percentage of errors of Unary gRPC Read requests (StoreAPI).",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "  sum by (namespace, job, grpc_code) (\n    rate(\n      grpc_server_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",grpc_method!=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n/ ignoring (grpc_code) group_left ()\n  sum by (namespace, job) (\n    rate(\n      grpc_server_handled_total{grpc_method!=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )",
     "legendFormat": "{{namespace}} {{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Unary gRPC Read duration",
   "type": "timeseries",
   "description": "Shows duration percentiles of handled Unary gRPC Read requests (StoreAPI).",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_method!=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p50 {{namespace}} {{job}}"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_method!=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p90 {{namespace}} {{job}}"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_method!=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p99 {{namespace}} {{job}}"
    }
   ]
  },
  {
   "title": "Read gRPC Stream (StoreAPI Series/Exemplars)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "Stream gRPC Read request rate",
   "type": "timeseries",
   "description": "Shows rate of handled Stream gRPC Read requests (StoreAPI Series/Exemplar calls).",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, grpc_method, grpc_code) (\n  rate(\n    grpc_server_handled_total{grpc_type=\"server_stream\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "{{namespace}} {{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Stream gRPC Read error rate",
   "type": "timeseries",
   "description": "Shows percentage of errors of Stream gRPC Read requests (StoreAPI Series/Exemplar calls).",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "  sum by (namespace, job, grpc_code) (\n    rate(\n      grpc_server_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",grpc_type=\"server_stream\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n/ ignoring (grpc_code) group_left ()\n  sum by (namespace, job) (\n    rate(\n      grpc_server_handled_total{grpc_type=\"server_stream\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )",
     "legendFormat": "{{namespace}} {{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Stream gRPC Read duration",
   "type": "timeseries",
   "description": "Shows duration percentiles of handled Stream gRPC Read requests (StoreAPI Series/Exemplar calls).",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_type=\"server_stream\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p50 {{namespace}} {{job}}"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_type=\"server_stream\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p90 {{namespace}} {{job}}"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_type=\"server_stream\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p99 {{namespace}} {{job}}"
    }
   ]
  },
  { "title": "Query Available Concurrency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Available Concurrent Capacity",
   "type": "timeseries",
   "description": "Shows available capacity of queriers to process concurrent queries in parallel.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "  max_over_time(\n    thanos_query_concurrent_gate_queries_max{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n  )\n-\n  avg_over_time(\n    thanos_query_concurrent_gate_queries_in_flight{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n  )",
     "legendFormat": "{{job}} {{pod}}"
    }
   ]
  },
  { "title": "DNS Lookups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "DNS Lookups",
   "type": "timeseries",
   "description": "Shows the rate of DNS lookups to discover StoreAPI endpoints.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job) (\n  rate(thanos_query_endpoints_dns_lookups_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "DNS Lookups Errors",
   "type": "timeseries",
   "description": "Shows the percentage of failures compared to total number of executed DNS lookups.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "  sum by (namespace, job) (\n    rate(thanos_query_endpoints_dns_failures_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n  )\n/\n  sum by (namespace, job) (\n    rate(thanos_query_endpoints_dns_lookups_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n  )",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Shows the CPU usage of the component.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Shows various memory usage metrics of the component.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "Alloc All {{pod}}"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "Alloc Heap {{pod}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Alloc Rate All {{pod}}"
    },
    {
     "expr": "rate(go_memstats_heap_alloc_bytes{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Alloc Rate Heap {{pod}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "Inuse Stack {{pod}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "Inuse Heap {{pod}}"
    },
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "Resident Memory {{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Shows the number of goroutines being used by the component.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "description": "Shows the Go garbage collection pause durations for the component.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "{{quantile}} - {{pod}}"
    }
   ]
  }
 ]
}