{
 "title": "Thanos / Compact / Overview",
 "tags": [
  "thanos",
  "compact"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(thanos_build_info{container=\"thanos-compact\"}, job)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(thanos_status{}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "TODO Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TODO Compaction Blocks",
   "type": "timeseries",
   "description": "Shows number of blocks planned to be compacted.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, job) (thanos_compact_todo_compaction_blocks{job=~\"$job\",namespace=\"$namespace\"})",
     "legendFormat": "{{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "TODO Compactions",
   "type": "timeseries",
   "description": "Shows number of compaction operations to be done.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, job) (thanos_compact_todo_compactions{job=~\"$job\",namespace=\"$namespace\"})",
     "legendFormat": "{{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "TODO Deletions",
   "type": "timeseries",
   "description": "Shows number of blocks that have crossed their retention periods.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, job) (thanos_compact_todo_deletion_blocks{job=~\"$job\",namespace=\"$namespace\"})",
     "legendFormat": "{{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "TODO Downsamples",
   "type": "timeseries",
   "description": "Shows number of blocks to be downsampled.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, job) (thanos_compact_todo_downsample_blocks{job=~\"$job\",namespace=\"$namespace\"})",
     "legendFormat": "{{job}} {{namespace}}"
    }
   ]
  },
  { "title": "Group Compactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Group Compactions",
   "type": "timeseries",
   "description": "Shows rate of execution of compaction operations against blocks in a bucket, split by compaction resolution.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, resolution) (\n  rate(thanos_compact_group_compactions_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "Resolution: {{resolution}} - {{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Group Compaction Errors",
   "type": "timeseries",
   "description": "Shows the percentage of errors compared to the total number of executed compaction operations against blocks stored in bucket.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum by (namespace, job) (\n      rate(thanos_compact_group_compactions_failures_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n    )\n  /\n    sum by (namespace, job) (\n      rate(thanos_compact_group_compactions_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n    )\n)\n*\n  100",
     "legendFormat": "{{job}} {{namespace}}"
    }
   ]
  },
  { "title": "Downsample Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Downsample Rate",
   "type": "timeseries",
   "description": "Shows rate of execution of downsample operations against blocks stored in a bucket, split by resolution.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, resolution) (\n  rate(thanos_compact_downsample_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "Resolution: {{resolution}} - {{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Downsample Errors",
   "type": "timeseries",
   "description": "Shows the percentage of downsample errors compared to the total number of downsample operations done on block in buckets.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum by (namespace, job) (\n      rate(thanos_compact_downsample_failed_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n    )\n  /\n    sum by (namespace, job) (\n      rate(thanos_compact_downsample_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n    )\n)\n*\n  100",
     "legendFormat": "{{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Downsample Durations",
   "type": "timeseries",
   "description": "Shows the p50, p90, and p99 of the time it takes to complete downsample operation against blocks in a bucket, split by resolution.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, resolution, le) (\n    rate(\n      thanos_compact_downsample_duration_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p50 Resolution: {{resolution}} - {{job}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, resolution, le) (\n    rate(\n      thanos_compact_downsample_duration_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p90 Resolution: {{resolution}} - {{job}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, resolution, le) (\n    rate(\n      thanos_compact_downsample_duration_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p99 Resolution: {{resolution}} - {{job}} {{namespace}}"
    }
   ]
  },
  { "title": "Sync Meta", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Sync Meta Rate",
   "type": "timeseries",
   "description": "Shows rate of syncing block meta files from bucket into memory.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job) (\n  rate(thanos_blocks_meta_syncs_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Sync Meta Errors",
   "type": "timeseries",
   "description": "Shows percentage of errors of meta file sync operation compared to total number of meta file syncs from bucket.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum by (namespace, job) (\n      rate(thanos_blocks_meta_sync_failures_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n    )\n  /\n    sum by (namespace, job) (\n      rate(thanos_blocks_meta_syncs_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n    )\n)\n*\n  100",
     "legendFormat": "{{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Sync Meta Durations",
   "type": "timeseries",
   "description": "Shows p50, p90 and p99 durations of the time it takes to sync meta files from blocks in bucket.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, le) (\n    rate(thanos_blocks_meta_sync_duration_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "p50 {{job}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, le) (\n    rate(thanos_blocks_meta_sync_duration_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "p90 {{job}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, le) (\n    rate(thanos_blocks_meta_sync_duration_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "p99 {{job}} {{namespace}}"
    }
   ]
  },
  { "title": "Block Deletion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Deletion Rate",
   "type": "timeseries",
   "description": "Shows the deletion rate of blocks already marked for deletion.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job) (\n  rate(thanos_compact_blocks_cleaned_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Deletion Errors",
   "type": "timeseries",
   "description": "Shows rate of deletion failures for blocks already marked for deletion.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job) (\n  rate(thanos_compact_block_cleanup_failures_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Marking Rate",
   "type": "timeseries",
   "description": "Shows the rate at which blocks are marked for deletion (from GC and retention policy).",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job) (\n  rate(\n    thanos_compact_blocks_marked_total{job=~\"$job\",marker=\"deletion-mark.json\",namespace=\"$namespace\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "{{job}} {{namespace}}"
    }
   ]
  },
  { "title": "Bucket Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Bucket Operations",
   "type": "timeseries",
   "description": "Shows rate of executions of operations against object storage bucket.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, operation) (\n  rate(thanos_objstore_bucket_operations_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}} {{operation}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Bucket Operation Errors",
   "type": "timeseries",
   "description": "Shows percentage of errors of operations against object storage bucket.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum by (namespace, job, operation) (\n      rate(thanos_objstore_bucket_operation_failures_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n    )\n  /\n    sum by (namespace, job, operation) (\n      rate(thanos_objstore_bucket_operations_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n    )\n)\n*\n  100",
     "legendFormat": "{{job}} {{operation}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Bucket Operation Latency",
   "type": "timeseries",
   "description": "Shows latency of operations against object storage bucket.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, operation, le) (\n    rate(\n      thanos_objstore_bucket_operation_duration_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p99 {{job}} {{operation}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, operation, le) (\n    rate(\n      thanos_objstore_bucket_operation_duration_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p90 {{job}} {{operation}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, operation, le) (\n    rate(\n      thanos_objstore_bucket_operation_duration_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p50 {{job}} {{operation}} {{namespace}}"
    }
   ]
  },
  { "title": "Halted Compactors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Halted Compactors",
   "type": "timeseries",
   "description": "Shows compactors that have been halted due to unexpected errors.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, job) (thanos_compact_halted{job=~\"$job\",namespace=\"$namespace\"})",
     "legendFormat": "{{job}} {{namespace}}"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Garbage Collection",
   "type": "timeseries",
   "description": "Shows rate of execution of removal of blocks, if their data is available as part of a block with a higher compaction level.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job) (\n  rate(thanos_compact_garbage_collection_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Errors",
   "type": "timeseries",
   "description": "Shows the percentage of garbage collection operations that resulted in errors.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum by (namespace, job) (\n      rate(\n        thanos_compact_garbage_collection_failures_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n      )\n    )\n  /\n    sum by (namespace, job) (\n      rate(thanos_compact_garbage_collection_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n    )\n)\n*\n  100",
     "legendFormat": "{{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Durations",
   "type": "timeseries",
   "description": "Shows p50, p90 and p99 of how long it takes to execute garbage collection operations.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, le) (\n    rate(\n      thanos_compact_garbage_collection_duration_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p50 {{job}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, le) (\n    rate(\n      thanos_compact_garbage_collection_duration_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p90 {{job}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, le) (\n    rate(\n      thanos_compact_garbage_collection_duration_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p99 {{job}} {{namespace}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Shows the CPU usage of the component.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Shows various memory usage metrics of the component.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "Alloc All {{pod}}"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "Alloc Heap {{pod}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Alloc Rate All {{pod}}"
    },
    {
     "expr": "rate(go_memstats_heap_alloc_bytes{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Alloc Rate Heap {{pod}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "Inuse Stack {{pod}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "Inuse Heap {{pod}}"
    },
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "Resident Memory {{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Shows the number of goroutines being used by the component.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "description": "Shows the Go garbage collection pause durations for the component.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "{{quantile}} - {{pod}}"
    }
   ]
  }
 ]
}