{
 "title": "Thanos / Query Frontend / Overview",
 "tags": [
  "thanos",
  "query-frontend"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(thanos_build_info{container=\"thanos-query-frontend\"}, job)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(thanos_status{}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Query Frontend API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Query Request Rate",
   "type": "timeseries",
   "description": "Shows rate of requests on query frontend API.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, handler, code) (\n  rate(http_requests_total{handler=\"query-frontend\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{code}} - {{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "timeseries",
   "description": "Shows rate of queries passing through Query Frontend.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, handler, code) (\n  rate(\n    thanos_query_frontend_queries_total{job=~\"$job\",namespace=\"$namespace\",op=\"query_range\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "{{code}} - {{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Query Error Rate",
   "type": "timeseries",
   "description": "Shows the percentage of errors compared to the total number of requests on query frontend API.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum by (namespace, job, code) (\n      rate(\n        http_requests_total{code=~\"5..\",handler=\"query-frontend\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n      )\n    )\n  / ignoring (code) group_left ()\n    sum by (namespace, job) (\n      rate(http_requests_total{handler=\"query-frontend\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n    )\n)\n*\n  100",
     "legendFormat": "{{code}} - {{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Query Duration",
   "type": "timeseries",
   "description": "Shows p50, p90 and p99 of the time taken to respond to a query via the query frontend API.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, le) (\n    rate(\n      http_request_duration_seconds_bucket{handler=\"query-frontend\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p50 {{job}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, le) (\n    rate(\n      http_request_duration_seconds_bucket{handler=\"query-frontend\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p90 {{job}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, le) (\n    rate(\n      http_request_duration_seconds_bucket{handler=\"query-frontend\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p99 {{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Query Frontend Cache Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Cache Requests",
   "type": "timeseries",
   "description": "Shows rate of cache requests by cortex.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, tripperware) (\n  rate(cortex_cache_request_duration_seconds_count{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{tripperware}} - {{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "timeseries",
   "description": "Shows rate of cache hits by cortex.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, tripperware) (\n  rate(cortex_cache_hits_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{tripperware}} - {{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "timeseries",
   "description": "Shows rate of cache misses by cortex.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, tripperware) (\n  rate(querier_cache_misses_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{tripperware}} - {{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Fetched Keys",
   "type": "timeseries",
   "description": "Shows rate of keys fetched from cache by cortex.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, tripperware) (\n  rate(cortex_cache_fetched_keys_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{tripperware}} - {{job}} {{namespace}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Shows the CPU usage of the component.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Shows various memory usage metrics of the component.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "Alloc All {{pod}}"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "Alloc Heap {{pod}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Alloc Rate All {{pod}}"
    },
    {
     "expr": "rate(go_memstats_heap_alloc_bytes{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Alloc Rate Heap {{pod}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "Inuse Stack {{pod}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "Inuse Heap {{pod}}"
    },
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "Resident Memory {{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Shows the number of goroutines being used by the component.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "description": "Shows the Go garbage collection pause durations for the component.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "{{quantile}} - {{pod}}"
    }
   ]
  }
 ]
}