{
 "title": "Thanos / Ruler / Overview",
 "tags": [
  "thanos",
  "ruler"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(thanos_build_info{container=\"thanos-ruler\"},job)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(thanos_status{}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Rule Group Evaluations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rule Group Evaluation Rate",
   "type": "timeseries",
   "description": "Shows the rate of rule group evaluations.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, rule_group, strategy) (\n  rate(prometheus_rule_evaluations_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{rule_group}} {{strategy}} - {{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Rule Group Evaluation Failures",
   "type": "timeseries",
   "description": "Shows the rate of failed rule group evaluations.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, rule_group, strategy) (\n  rate(prometheus_rule_evaluation_failures_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{rule_group}} {{strategy}} - {{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Rule Group Evaluations Missed",
   "type": "timeseries",
   "description": "Shows rate of rule group evaluations missed due to slow rule evaluations.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, rule_group, strategy) (\n  rate(prometheus_rule_group_iterations_missed_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{rule_group}} {{strategy}} - {{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Rule Group Evaluations Too Slow",
   "type": "timeseries",
   "description": "Shows rule groups with evaluations taking longer than their set interval.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(\n    sum by (namespace, job, rule_group) (\n      prometheus_rule_group_last_duration_seconds{job=~\"$job\",namespace=\"$namespace\"}\n    )\n  >\n    sum by (namespace, job, rule_group) (\n      prometheus_rule_group_interval_seconds{job=~\"$job\",namespace=\"$namespace\"}\n    )\n)",
     "legendFormat": "{{rule_group}} - {{job}} {{namespace}}"
    }
   ]
  },
  { "title": "Alerts Sent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Alerts Sent",
   "type": "timeseries",
   "description": "Shows rate of alerts sent by ruler.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, alertmanager) (\n  rate(thanos_alert_sender_alerts_sent_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{alertmanager}} - {{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Alerts Dropped",
   "type": "timeseries",
   "description": "Shows rate of alerts dropped by Ruler when sending.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, alertmanager) (\n  rate(thanos_alert_sender_alerts_dropped_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{alertmanager}} - {{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Alert Sending Errors",
   "type": "timeseries",
   "description": "Shows percentage of alert sending operations that have resulted in errors.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "  sum by (namespace, job) (\n    rate(thanos_alert_sender_errors_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n  )\n/\n  sum by (namespace, job) (\n    rate(thanos_alert_sender_alerts_sent_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n  )",
     "legendFormat": "{{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Alert Sending Durations",
   "type": "timeseries",
   "description": "Shows p50, p90 and p99 durations for alerts being sent from the ruler.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, le) (\n    rate(thanos_alert_sender_latency_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "p50 {{job}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, le) (\n    rate(thanos_alert_sender_latency_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "p90 {{job}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, le) (\n    rate(thanos_alert_sender_latency_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "p99 {{job}} {{namespace}}"
    }
   ]
  },
  { "title": "Alert Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Alert Queue Pushed",
   "type": "timeseries",
   "description": "Shows the rate of alerts being pushed to sender queue.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job) (\n  rate(thanos_alert_queue_alerts_pushed_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Alert Queue Popped",
   "type": "timeseries",
   "description": "Shows rate of alerts popped from queue, to be sent to Alertmanagers.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job) (\n  rate(thanos_alert_queue_alerts_popped_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Dropped Percentage",
   "type": "timeseries",
   "description": "Shows percentage of alerts dropped as compared to alerts being queued for sending.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "  sum by (namespace, job) (\n    rate(thanos_alert_queue_alerts_dropped_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n  )\n/\n  sum by (namespace, job) (\n    rate(thanos_alert_queue_alerts_pushed_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n  )",
     "legendFormat": "{{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Read gRPC Unary (StoreAPI Info/Labels)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "Unary gRPC Read request rate",
   "type": "timeseries",
   "description": "Shows rate of handled Unary gRPC Read requests (StoreAPI).",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, grpc_method, grpc_code) (\n  rate(\n    grpc_server_handled_total{grpc_method!=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "{{namespace}} {{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Unary gRPC Read error rate",
   "type": "timeseries",
   "description": "Shows percentage of errors of Unary gRPC Read requests (StoreAPI).",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "  sum by (namespace, job, grpc_code) (\n    rate(\n      grpc_server_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",grpc_method!=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n/ ignoring (grpc_code) group_left ()\n  sum by (namespace, job) (\n    rate(\n      grpc_server_handled_total{grpc_method!=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )",
     "legendFormat": "{{namespace}} {{job}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Unary gRPC Read duration",
   "type": "timeseries",
   "description": "Shows duration percentiles of handled Unary gRPC Read requests (StoreAPI).",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_method!=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p50 {{namespace}} {{job}}"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_method!=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p90 {{namespace}} {{job}}"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_method!=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p99 {{namespace}} {{job}}"
    }
   ]
  },
  {
   "title": "Read gRPC Stream (StoreAPI Series/Exemplars)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 }
  },
  {
   "title": "Stream gRPC Read request rate",
   "type": "timeseries",
   "description": "Shows rate of handled Stream gRPC Read requests (StoreAPI Series/Exemplar calls).",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, grpc_method, grpc_code) (\n  rate(\n    grpc_server_handled_total{grpc_type=\"server_stream\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "{{namespace}} {{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Stream gRPC Read error rate",
   "type": "timeseries",
   "description": "Shows percentage of errors of Stream gRPC Read requests (StoreAPI Series/Exemplar calls).",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "  sum by (namespace, job, grpc_code) (\n    rate(\n      grpc_server_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",grpc_type=\"server_stream\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n/ ignoring (grpc_code) group_left ()\n  sum by (namespace, job) (\n    rate(\n      grpc_server_handled_total{grpc_type=\"server_stream\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )",
     "legendFormat": "{{namespace}} {{job}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Stream gRPC Read duration",
   "type": "timeseries",
   "description": "Shows duration percentiles of handled Stream gRPC Read requests (StoreAPI Series/Exemplar calls).",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_type=\"server_stream\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p50 {{namespace}} {{job}}"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_type=\"server_stream\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p90 {{namespace}} {{job}}"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_type=\"server_stream\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p99 {{namespace}} {{job}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Shows the CPU usage of the component.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Shows various memory usage metrics of the component.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "Alloc All {{pod}}"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "Alloc Heap {{pod}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Alloc Rate All {{pod}}"
    },
    {
     "expr": "rate(go_memstats_heap_alloc_bytes{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Alloc Rate Heap {{pod}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "Inuse Stack {{pod}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "Inuse Heap {{pod}}"
    },
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "Resident Memory {{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Shows the number of goroutines being used by the component.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "description": "Shows the Go garbage collection pause durations for the component.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "{{quantile}} - {{pod}}"
    }
   ]
  }
 ]
}