{
 "title": "Thanos / Store Gateway / Overview",
 "tags": [
  "thanos",
  "store"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(thanos_build_info{container=\"thanos-store\"}, job)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(thanos_status{}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Read gRPC Unary (StoreAPI Info/Labels)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Unary gRPC Read request rate",
   "type": "timeseries",
   "description": "Shows rate of handled Unary gRPC Read requests (StoreAPI).",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, grpc_method, grpc_code) (\n  rate(\n    grpc_server_handled_total{grpc_method!=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "{{namespace}} {{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Unary gRPC Read error rate",
   "type": "timeseries",
   "description": "Shows percentage of errors of Unary gRPC Read requests (StoreAPI).",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum by (namespace, job, grpc_code) (\n      rate(\n        grpc_server_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",grpc_method!=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n      )\n    )\n  / ignoring (grpc_code) group_left ()\n    sum by (namespace, job) (\n      rate(\n        grpc_server_handled_total{grpc_method!=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n      )\n    )\n)\n*\n  100",
     "legendFormat": "{{namespace}} {{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Unary gRPC Read duration",
   "type": "timeseries",
   "description": "Shows duration percentiles of handled Unary gRPC Read requests (StoreAPI).",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_method!=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p50 {{namespace}} {{job}}"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_method!=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p90 {{namespace}} {{job}}"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_method!=\"RemoteWrite\",grpc_type=\"unary\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p99 {{namespace}} {{job}}"
    }
   ]
  },
  {
   "title": "Read gRPC Stream (StoreAPI Series/Exemplars)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Stream gRPC Read request rate",
   "type": "timeseries",
   "description": "Shows rate of handled Stream gRPC Read requests (StoreAPI Series/Exemplar calls).",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, grpc_method, grpc_code) (\n  rate(\n    grpc_server_handled_total{grpc_type=\"server_stream\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "{{namespace}} {{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Stream gRPC Read error rate",
   "type": "timeseries",
   "description": "Shows percentage of errors of Stream gRPC Read requests (StoreAPI Series/Exemplar calls).",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum by (namespace, job, grpc_code) (\n      rate(\n        grpc_server_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",grpc_type=\"server_stream\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n      )\n    )\n  / ignoring (grpc_code) group_left ()\n    sum by (namespace, job) (\n      rate(\n        grpc_server_handled_total{grpc_type=\"server_stream\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n      )\n    )\n)\n*\n  100",
     "legendFormat": "{{namespace}} {{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Stream gRPC Read duration",
   "type": "timeseries",
   "description": "Shows duration percentiles of handled Stream gRPC Read requests (StoreAPI Series/Exemplar calls).",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_type=\"server_stream\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p50 {{namespace}} {{job}}"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_type=\"server_stream\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p90 {{namespace}} {{job}}"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, le) (\n    rate(\n      grpc_server_handling_seconds_bucket{grpc_type=\"server_stream\",job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p99 {{namespace}} {{job}}"
    }
   ]
  },
  { "title": "Bucket Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Bucket Operations",
   "type": "timeseries",
   "description": "Shows rate of executions of operations against object storage bucket.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, operation) (\n  rate(thanos_objstore_bucket_operations_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}} {{operation}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Bucket Operation Errors",
   "type": "timeseries",
   "description": "Shows percentage of errors of operations against object storage bucket.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum by (namespace, job, operation) (\n      rate(thanos_objstore_bucket_operation_failures_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n    )\n  /\n    sum by (namespace, job, operation) (\n      rate(thanos_objstore_bucket_operations_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n    )\n)\n*\n  100",
     "legendFormat": "{{job}} {{operation}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Bucket Operation Latency",
   "type": "timeseries",
   "description": "Shows latency of operations against object storage bucket.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, operation, le) (\n    rate(\n      thanos_objstore_bucket_operation_duration_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p50 {{job}} {{operation}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, operation, le) (\n    rate(\n      thanos_objstore_bucket_operation_duration_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p90 {{job}} {{operation}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, operation, le) (\n    rate(\n      thanos_objstore_bucket_operation_duration_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p99 {{job}} {{operation}} {{namespace}}"
    }
   ]
  },
  { "title": "Block Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Block Load Rate",
   "type": "timeseries",
   "description": "Shows the rate of block loads from the bucket.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job) (\n  rate(thanos_bucket_store_block_loads_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Block Load Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to total number of block load operations.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum by (namespace, job) (\n      rate(thanos_bucket_store_block_load_failures_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n    )\n  /\n    sum by (namespace, job) (\n      rate(thanos_bucket_store_block_loads_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n    )\n)\n*\n  100",
     "legendFormat": "{{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Block Drop Rate",
   "type": "timeseries",
   "description": "Shows rate of block drops.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, operation) (\n  rate(thanos_bucket_store_block_drops_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}} {{operation}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Block Drop Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to total number of block drops.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum by (namespace, job) (\n      rate(thanos_bucket_store_block_drop_failures_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n    )\n  /\n    sum by (namespace, job) (\n      rate(thanos_bucket_store_block_drops_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n    )\n)\n*\n  100",
     "legendFormat": "{{job}} {{namespace}}"
    }
   ]
  },
  { "title": "Cache Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Cache Requests",
   "type": "timeseries",
   "description": "Shows rate of cache requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, item_type) (\n  rate(thanos_store_index_cache_requests_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}} {{item_type}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "timeseries",
   "description": "Shows rate of cache hits.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, item_type) (\n  rate(thanos_store_index_cache_hits_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}} {{item_type}} {{namespace}}"
    }
   ]
  },
  { "title": "Query Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Blocks Queried",
   "type": "timeseries",
   "description": "Shows the mean rate, p50, p90 and p99 for the amount of blocks touched whilst evaluating queries.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, job) (\n  rate(thanos_bucket_store_series_blocks_queried_sum{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)\n/\nsum by (namespace, job) (\n  rate(thanos_bucket_store_series_blocks_queried_count{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "mean {{job}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, le) (\n    rate(\n      thanos_bucket_store_series_blocks_queried_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p50 {{job}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, le) (\n    rate(\n      thanos_bucket_store_series_blocks_queried_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p90 {{job}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, le) (\n    rate(\n      thanos_bucket_store_series_blocks_queried_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p99 {{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Data Fetched",
   "type": "timeseries",
   "description": "Shows the mean rate, p50, p90 and p99 of the amount of data fetched to fulfill Store API calls, split by data type.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, data_type) (\n  rate(\n    thanos_bucket_store_series_data_size_fetched_bytes_sum{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n  )\n)\n/\nsum by (namespace, job, data_type) (\n  rate(\n    thanos_bucket_store_series_data_size_fetched_bytes_count{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "mean {{job}} {{data_type}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, data_type, le) (\n    rate(\n      thanos_bucket_store_series_data_size_fetched_bytes_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p50 {{job}} {{data_type}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, data_type, le) (\n    rate(\n      thanos_bucket_store_series_data_size_fetched_bytes_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p90 {{job}} {{data_type}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, data_type, le) (\n    rate(\n      thanos_bucket_store_series_data_size_fetched_bytes_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p99 {{job}} {{data_type}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Data Touched",
   "type": "timeseries",
   "description": "Shows the mean rate, p50, p90 and p99 of the amount of data touched to fulfill Store API calls, split by data type.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, data_type) (\n  rate(\n    thanos_bucket_store_series_data_size_touched_bytes_sum{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n  )\n)\n/\nsum by (namespace, job, data_type) (\n  rate(\n    thanos_bucket_store_series_data_size_touched_bytes_count{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "mean {{job}} {{data_type}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, data_type, le) (\n    rate(\n      thanos_bucket_store_series_data_size_touched_bytes_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p50 {{job}} {{data_type}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, data_type, le) (\n    rate(\n      thanos_bucket_store_series_data_size_touched_bytes_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p90 {{job}} {{data_type}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, data_type, le) (\n    rate(\n      thanos_bucket_store_series_data_size_touched_bytes_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p99 {{job}} {{data_type}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Result Series",
   "type": "timeseries",
   "description": "Shows the mean rate, p50, p90 and p99 of the count of result series observed in the final result of queries.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, job) (\n  rate(thanos_bucket_store_series_result_series_sum{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)\n/\nsum by (namespace, job) (\n  rate(thanos_bucket_store_series_result_series_count{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "mean {{job}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, le) (\n    rate(thanos_bucket_store_series_result_series_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "p50 {{job}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, le) (\n    rate(thanos_bucket_store_series_result_series_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "p90 {{job}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, le) (\n    rate(thanos_bucket_store_series_result_series_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "p99 {{job}} {{namespace}}"
    }
   ]
  },
  { "title": "Query Operation Durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Get All Series Duration",
   "type": "timeseries",
   "description": "Shows the p50, p90 and p99 of time it takes until all per-block prepares and loads for each query is finished.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, le) (\n    rate(\n      thanos_bucket_store_series_get_all_duration_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p50 {{job}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, le) (\n    rate(\n      thanos_bucket_store_series_get_all_duration_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p90 {{job}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, le) (\n    rate(\n      thanos_bucket_store_series_get_all_duration_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p99 {{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Merge Durations",
   "type": "timeseries",
   "description": "Shows the p50, p90 and p99 of the time it takes to merge sub-results from all queried blocks into single results for queries.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, le) (\n    rate(\n      thanos_bucket_store_series_merge_duration_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p50 {{job}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, le) (\n    rate(\n      thanos_bucket_store_series_merge_duration_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p90 {{job}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, le) (\n    rate(\n      thanos_bucket_store_series_merge_duration_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p99 {{job}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Gate Waiting Durations",
   "type": "timeseries",
   "description": "Shows the p50, p90 and p99 of the time it took for queries to wait at the gate.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, le) (\n    rate(\n      thanos_bucket_store_series_gate_queries_duration_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p50 {{job}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, le) (\n    rate(\n      thanos_bucket_store_series_gate_queries_duration_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p90 {{job}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, le) (\n    rate(\n      thanos_bucket_store_series_gate_queries_duration_seconds_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p99 {{job}} {{namespace}}"
    }
   ]
  },
  { "title": "Store Sent Chunk Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Store Sent Chunk Size",
   "type": "timeseries",
   "description": "Shows the mean rate, p50, p90 and p99 for the bytes of chunks sent for single series, which are adequate to the gRPC message size sent to querier.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, job) (\n  rate(thanos_bucket_store_sent_chunk_size_bytes_sum{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)\n/\nsum by (namespace, job) (\n  rate(thanos_bucket_store_sent_chunk_size_bytes_count{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])\n)",
     "legendFormat": "mean {{job}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (namespace, job, le) (\n    rate(\n      thanos_bucket_store_sent_chunk_size_bytes_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p50 {{job}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (namespace, job, le) (\n    rate(\n      thanos_bucket_store_sent_chunk_size_bytes_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p90 {{job}} {{namespace}}"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, job, le) (\n    rate(\n      thanos_bucket_store_sent_chunk_size_bytes_bucket{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "p99 {{job}} {{namespace}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Shows the CPU usage of the component.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Shows various memory usage metrics of the component.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "Alloc All {{pod}}"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "Alloc Heap {{pod}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Alloc Rate All {{pod}}"
    },
    {
     "expr": "rate(go_memstats_heap_alloc_bytes{job=~\"$job\",namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Alloc Rate Heap {{pod}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "Inuse Stack {{pod}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "Inuse Heap {{pod}}"
    },
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "Resident Memory {{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Shows the number of goroutines being used by the component.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "description": "Shows the Go garbage collection pause durations for the component.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=~\"$job\",namespace=\"$namespace\"}",
     "legendFormat": "{{quantile}} - {{pod}}"
    }
   ]
  }
 ]
}