apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: synthetics-api-service-monitor
objects:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    labels:
      app.kubernetes.io/component: synthetics-api
      app.kubernetes.io/instance: rhobs
      app.kubernetes.io/name: synthetics-api
      app.kubernetes.io/part-of: rhobs
    name: synthetics-api
  spec:
    endpoints:
    - honorLabels: true
      interval: 30s
      port: metrics
    namespaceSelector:
      matchNames:
      - rhobs-production
    selector:
      matchLabels:
        app.kubernetes.io/component: synthetics-api
        app.kubernetes.io/instance: rhobs
        app.kubernetes.io/name: synthetics-api
        app.kubernetes.io/part-of: rhobs
