# This is a dirty hack commited manually. Please forgive me. Don't tell anyone. Don't delete until load test completion.
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: synthetics-api-service-monitor
objects:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    labels:
      app.kubernetes.io/component: synthetics-api
      prometheus: app-sre
    name: synthetics-api
    namespace: openshift-customer-monitoring
  spec:
    endpoints:
    - honorLabels: true
      interval: 30s
      path: /metrics
      port: metrics
    namespaceSelector:
      matchNames:
      - rhobs-int
    selector:
      matchLabels:
        app.kubernetes.io/component: synthetics-api
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    labels:
      app.kubernetes.io/component: synthetics-agent
      prometheus: app-sre
    name: synthetics-agent
    namespace: openshift-customer-monitoring
  spec:
    endpoints:
      - honorLabels: true
        interval: 30s
        path: /metrics
        port: metrics
    namespaceSelector:
      matchNames:
        - rhobs-int
    selector:
      matchLabels:
        app.kubernetes.io/component: synthetics-agent
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    labels:
      app.kubernetes.io/name: blackbox-exporter
      prometheus: app-sre
    name: synthetics-bb-exporter
    namespace: openshift-customer-monitoring
  spec:
    endpoints:
      - honorLabels: true
        interval: 30s
        path: /metrics
        port: metrics
    namespaceSelector:
      matchNames:
        - rhobs-int
    selector:
      matchLabels:
        app.kubernetes.io/name: blackbox-exporter
