apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: synthetics-api
    app.kubernetes.io/instance: rhobs
    app.kubernetes.io/name: synthetics-api
    app.kubernetes.io/part-of: rhobs
    app.kubernetes.io/version: cea7d4656cd0ad338e580cc6ba266264a9938e5c
  name: synthetics-api
  namespace: rhobs-int
