apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: synthetics-api
    app.kubernetes.io/instance: rhobs
    app.kubernetes.io/name: synthetics-api
    app.kubernetes.io/part-of: rhobs
    app.kubernetes.io/version: cea7d4656cd0ad338e580cc6ba266264a9938e5c
  name: synthetics-api
  namespace: rhobs-int
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: synthetics-api
subjects:
- kind: ServiceAccount
  name: synthetics-api
  namespace: rhobs-int
