apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: synthetics-agent
    app.kubernetes.io/instance: rhobs
    app.kubernetes.io/name: synthetics-agent
    app.kubernetes.io/part-of: rhobs
    app.kubernetes.io/version: "3012046"
  name: synthetics-agent
  namespace: rhobs-int
