apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: thanos-operator
    app.kubernetes.io/instance: thanosreceive-viewer-role
    app.kubernetes.io/managed-by: rhobs
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: thanos-operator
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: thanos-operator-thanosreceive-viewer-role
rules:
- apiGroups:
  - monitoring.thanos.io
  resources:
  - thanosreceives
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.thanos.io
  resources:
  - thanosreceives/status
  verbs:
  - get
