apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: thanos-bucket-cache-memcached
  name: thanos-bucket-cache-memcached
  namespace: rhobs-production
stringData:
  thanos.yaml: |
    type: MEMCACHED
    config:
      addresses:
      - dnssrv+_client._tcp.thanos-bucket-cache.rhobs-production.svc
      timeout: 2s
      max_idle_connections: 1100
      max_async_concurrency: 50
      max_async_buffer_size: 25000
      max_get_multi_concurrency: 1000
      max_item_size: 0
      max_get_multi_batch_size: 100
      dns_provider_update_interval: 10s
      auto_discovery: false
      set_async_circuit_breaker_config:
        enabled: false
        half_open_max_requests: 0
        open_duration: 0s
        min_requests: 0
        consecutive_failures: 0
        failure_percent: 0
    chunk_subrange_size: 16000
    max_chunks_get_range_requests: 3
    metafile_max_size: 0
    chunk_object_attrs_ttl: 24h0m0s
    chunk_subrange_ttl: 24h0m0s
    blocks_iter_ttl: 0s
    metafile_exists_ttl: 2h0m0s
    metafile_doesnt_exist_ttl: 15m0s
    metafile_content_ttl: 24h0m0s
type: Opaque
