#!/bin/bash
# Generate hcp.yaml from split domain files in hcp/ directory
# This script combines all split Template files into a single hcp.yaml

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HCP_DIR="${SCRIPT_DIR}/../resources/tenant-rules/hcp"
OUTPUT_FILE="${SCRIPT_DIR}/../resources/tenant-rules/hcp.yaml"

# Check if yq is available
if ! command -v yq &> /dev/null; then
    echo "Error: yq is required but not installed." >&2
    exit 1
fi

# Define the order of files to process (controls order in output)
FILES=(
    "audit.yaml"
    "billing.yaml"
    "nodes.yaml"
    "oauth.yaml"
    "observability.yaml"
    "cluster-operators.yaml"
    "control-plane.yaml"
    "api-server.yaml"
    "splunk.yaml"
)

# Create temporary files
TEMP_OBJECTS=$(mktemp)
trap "rm -f $TEMP_OBJECTS" EXIT

# Collect all objects from all files into a JSON array
echo "[]" > "$TEMP_OBJECTS"

for file in "${FILES[@]}"; do
    filepath="${HCP_DIR}/${file}"
    if [[ -f "$filepath" ]]; then
        # Extract objects array and append to our collection
        yq eval -o=json '.objects' "$filepath" > /tmp/current_objects.json
        yq eval-all -o=json '. as $item ireduce ([]; . + $item)' "$TEMP_OBJECTS" /tmp/current_objects.json > /tmp/merged.json
        mv /tmp/merged.json "$TEMP_OBJECTS"
    else
        echo "Warning: ${filepath} not found, skipping" >&2
    fi
done

# Build the final template with auto-generated warning
cat > "$OUTPUT_FILE" << 'HEADER'
# ============================================================================
# WARNING: This file is auto-generated from resources/tenant-rules/hcp/*.yaml
# DO NOT EDIT THIS FILE DIRECTLY!
#
# To modify HCP tenant rules:
#   1. Edit the appropriate file in resources/tenant-rules/hcp/
#   2. Run: make hcp-rules
#   3. Commit both the source file and this generated file
#
# Source files:
#   - hcp/api-server.yaml      (kube-apiserver, openshift-apiserver, SLOs)
#   - hcp/audit.yaml           (audit webhook CloudWatch)
#   - hcp/billing.yaml         (billing metrics)
#   - hcp/cluster-operators.yaml (ClusterOperator health)
#   - hcp/control-plane.yaml   (etcd, kube-controller-manager, kube-scheduler)
#   - hcp/nodes.yaml           (node health, nodepool, autoscaler)
#   - hcp/oauth.yaml           (OAuth service health)
#   - hcp/observability.yaml   (watchdog, prometheus targets)
#   - hcp/splunk.yaml          (SAE deployment)
# ============================================================================
HEADER

yq eval -n '{
  "apiVersion": "template.openshift.io/v1",
  "kind": "Template",
  "metadata": {
    "name": "rhobs-hcp-rules",
    "annotations": {
      "description": "Template for deploying HCP rules to RHOBS"
    }
  },
  "parameters": [
    {"name": "NAMESPACE", "description": "Namespace to deploy the rules to", "required": true},
    {"name": "TENANT", "description": "Tenant to deploy the rules to", "required": true}
  ]
}' >> "$OUTPUT_FILE"

# Add the objects array
yq eval -i ".objects = $(cat $TEMP_OBJECTS)" "$OUTPUT_FILE"

echo "Generated ${OUTPUT_FILE}"
