#!/bin/bash
# Generate sc.yaml from split domain files in sc/ directory
# This script combines all split Template files into a single sc.yaml

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SC_DIR="${SCRIPT_DIR}/../resources/tenant-rules/sc"
OUTPUT_FILE="${SCRIPT_DIR}/../resources/tenant-rules/sc.yaml"

# Check if yq is available
if ! command -v yq &> /dev/null; then
    echo "Error: yq is required but not installed." >&2
    exit 1
fi

# Define the order of files to process (controls order in output)
FILES=(
    "acm-managed-clusters.yaml"
    "acm-grc.yaml"
    "acm-manifestwork.yaml"
    "cert-manager.yaml"
    "observability.yaml"
)

# Create temporary files
TEMP_OBJECTS=$(mktemp)
trap "rm -f $TEMP_OBJECTS" EXIT

# Collect all objects from all files into a JSON array
echo "[]" > "$TEMP_OBJECTS"

for file in "${FILES[@]}"; do
    filepath="${SC_DIR}/${file}"
    if [[ -f "$filepath" ]]; then
        # Extract objects array and append to our collection
        yq eval -o=json '.objects' "$filepath" > /tmp/current_objects.json
        yq eval-all -o=json '. as $item ireduce ([]; . + $item)' "$TEMP_OBJECTS" /tmp/current_objects.json > /tmp/merged.json
        mv /tmp/merged.json "$TEMP_OBJECTS"
    else
        echo "Warning: ${filepath} not found, skipping" >&2
    fi
done

# Build the final template with auto-generated warning
cat > "$OUTPUT_FILE" << 'HEADER'
# ============================================================================
# WARNING: This file is auto-generated from resources/tenant-rules/sc/*.yaml
# DO NOT EDIT THIS FILE DIRECTLY!
#
# To modify SC tenant rules:
#   1. Edit the appropriate file in resources/tenant-rules/sc/
#   2. Run: make sc-rules
#   3. Commit both the source file and this generated file
#
# Source files:
#   - sc/acm-managed-clusters.yaml  (ACM managed cluster condition alerts)
#   - sc/acm-grc.yaml              (ACM GRC policy controller alerts)
#   - sc/acm-manifestwork.yaml     (ACM ManifestWork failure alerts)
#   - sc/cert-manager.yaml         (TLS certificate health alerts)
#   - sc/observability.yaml        (DeadMansSnitch watchdog)
# ============================================================================
HEADER

yq eval -n '{
  "apiVersion": "template.openshift.io/v1",
  "kind": "Template",
  "metadata": {
    "name": "rhobs-sc-rules",
    "annotations": {
      "description": "Template for deploying SC rules to RHOBS"
    }
  },
  "parameters": [
    {"name": "NAMESPACE", "description": "Namespace to deploy the rules to", "required": true},
    {"name": "TENANT", "description": "Tenant to deploy the rules to", "required": true}
  ]
}' >> "$OUTPUT_FILE"

# Add the objects array
yq eval -i ".objects = $(cat $TEMP_OBJECTS)" "$OUTPUT_FILE"

echo "Generated ${OUTPUT_FILE}"
