apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: thanos-query-frontend
    app.kubernetes.io/managed-by: thanos-operator
    app.kubernetes.io/name: thanos-query-frontend
    app.kubernetes.io/part-of: thanos
    prometheus: app-sre
  name: thanos-query-frontend
  namespace: openshift-customer-monitoring
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: public
  namespaceSelector:
    matchNames:
    - rhobs-stage
  selector:
    matchLabels:
      app.kubernetes.io/component: thanos-query-frontend
      app.kubernetes.io/managed-by: thanos-operator
      app.kubernetes.io/name: thanos-query-frontend
      app.kubernetes.io/part-of: thanos
