package main

import (
	"fmt"
	"os"

	"github.com/bwplotka/mimic"
	"github.com/bwplotka/mimic/encoding"
	"github.com/go-kit/log"
	"github.com/observatorium/observatorium/configuration_go/kubegen/openshift"
	templatev1 "github.com/openshift/api/template/v1"
	"github.com/rhobs/configuration/clusters"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	rbacv1 "k8s.io/api/rbac/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
	"k8s.io/utils/ptr"
)

const (
	// Images from konflux-tempo bundle
	tempoOperatorImage = "quay.io/redhat-user-workloads/rhosdt-tenant/tempo/tempo-operator"
	tempoImage         = "quay.io/redhat-user-workloads/rhosdt-tenant/tempo/tempo"
	tempoQueryImage    = "quay.io/redhat-user-workloads/rhosdt-tenant/tempo/tempo-query"
	tempoGatewayImage  = "quay.io/redhat-user-workloads/rhosdt-tenant/tempo/tempo-gateway"
	tempoOPAImage      = "quay.io/redhat-user-workloads/rhosdt-tenant/tempo/tempo-opa"

	// Image SHAs from bundle.env (these should be updated via mage sync:operator)
	tempoOperatorVersion = "37b306933e7216e8744627dbbc0fa917e989c03a"
	tempoVersion         = "sha256:60feffb68790178c5b8d90be0d16e6b943678a636369a2ebbdca4c37e5152439"
	tempoQueryVersion    = "sha256:005430fb7fb525f3dfecbdbce99d54b1fbf0a15bcdf9ee088a03b8e12b78d68e"
	tempoGatewayVersion  = "sha256:f111b4fb738bf95ce0d85e7de23e1bf6a2143317a853a4dadd030768f5bd72b1"
	tempoOPAVersion      = "sha256:0aa7a36561c46a720ace5ecd8c97a5bca5be51d0b95f1166b884598bb4174767"

	// tempoOperatorCRDRef is the commit ref used to sync the Tempo Operator CRDs
	// from the github.com/os-observability/konflux-tempo repository.
	// This is generated by mage sync:operator and should not be modified manually in normal circumstances.
	tempoOperatorCRDRef = "fd473ff3c87c9a24cf775a2ccefdc82ac6226d75"
)

// TempoOperatorCRDS Generates the CRDs for the Tempo operator.
// This is synced from the ref tempoOperatorCRDRef at https://github.com/grafana/tempo-operator
func (b Build) TempoOperatorCRDS(config clusters.ClusterConfig) error {
	// For migrated clusters, CRDs are handled in traces bundle
	if isMigratedCluster(config) {
		return nil // CRDs are generated as part of traces bundle
	}
	gen := b.generator(config, "tempo-operator-crds")
	return tempoCRD(gen, clusters.ProductionMaps)
}

func tempoCRD(gen *mimic.Generator, templates clusters.TemplateMaps) error {
	const (
		tempostacks     = "tempo.grafana.com_tempostacks.yaml"
		tempomonolithic = "tempo.grafana.com_tempomonolithics.yaml"
		base            = "https://raw.githubusercontent.com/openshift/grafana-tempo-operator/" + tempoOperatorCRDRef + "/bundle/openshift/manifests/"
	)

	var objs []runtime.Object
	for _, component := range []string{tempostacks, tempomonolithic} {
		crd, err := getCustomResourceDefinition(base + component)
		if err != nil {
			return err
		}

		objs = append(objs, crd)
	}

	logger := log.NewLogfmtLogger(log.NewSyncWriter(os.Stdout))
	_ = logger.Log("msg", "successfully fetched CRD objects", "count", len(objs))

	gen.Add("crds.yaml", encoding.GhodssYAML(
		openshift.WrapInTemplate(
			objs,
			metav1.ObjectMeta{Name: "tempo-operator-crds"},
			[]templatev1.Parameter{},
		),
	))
	gen.Generate()
	return nil
}

func (b Build) TempoOperator(config clusters.ClusterConfig) {
	// For migrated clusters, operator is handled in traces bundle
	if isMigratedCluster(config) {
		return // Operator is generated as part of traces bundle
	}

	gen := b.generator(config, "tempo-operator")

	objs := tempoOperatorResources(config.Namespace)

	gen.Add("tempo-operator.yaml", encoding.GhodssYAML(
		openshift.WrapInTemplate(objs, metav1.ObjectMeta{Name: "tempo-operator-manager"}, []templatev1.Parameter{}),
	))
	gen.Generate()
}

func tempoOperatorResources(namespace string) []runtime.Object {
	objs := []runtime.Object{
		NewTempoControllerManagerDeployment(namespace),
		NewTempoServiceAccountControllerManager(namespace),
		NewTempoClusterRoleManager(),
		NewTempoClusterRoleBindingManager(namespace),
		NewTempoStackEditorClusterRole(),
		NewTempoStackViewerClusterRole(),
		NewTempoMonolithicEditorClusterRole(),
		NewTempoMonolithicViewerClusterRole(),
		NewTempoPrometheusRole(namespace),
		NewTempoPrometheusRoleBinding(namespace),
		NewTempoLeaderElectionRole(namespace),
		NewTempoLeaderElectionRoleBinding(namespace),
		NewTempoMetricsReaderClusterRole(),
		NewTempoMetricsService(namespace),
		NewTempoClusterMonitoringViewBinding(namespace),
		NewTempoWebhookService(namespace),
	}
	return objs
}

// NewTempoControllerManagerDeployment returns the Deployment for the tempo operator controller-manager.
func NewTempoControllerManagerDeployment(namespace string) *appsv1.Deployment {
	return &appsv1.Deployment{
		TypeMeta: metav1.TypeMeta{
			APIVersion: appsv1.SchemeGroupVersion.String(),
			Kind:       "Deployment",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "tempo-operator-controller",
			Namespace: namespace,
			Labels: map[string]string{
				"app.kubernetes.io/name":      "tempo-operator",
				"app.kubernetes.io/component": "controller",
				"control-plane":               "controller-manager",
			},
		},
		Spec: appsv1.DeploymentSpec{
			Replicas: ptr.To(int32(1)),
			Selector: &metav1.LabelSelector{
				MatchLabels: map[string]string{
					"app.kubernetes.io/name":      "tempo-operator",
					"app.kubernetes.io/component": "controller",
				},
			},
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{
					Labels: map[string]string{
						"app.kubernetes.io/name":      "tempo-operator",
						"app.kubernetes.io/component": "controller",
					},
					Annotations: map[string]string{
						"kubectl.kubernetes.io/default-container": "manager",
					},
				},
				Spec: corev1.PodSpec{
					ServiceAccountName: "tempo-operator-controller-manager",
					SecurityContext: &corev1.PodSecurityContext{
						RunAsNonRoot: ptr.To(true),
						SeccompProfile: &corev1.SeccompProfile{
							Type: corev1.SeccompProfileTypeRuntimeDefault,
						},
					},
					Containers: []corev1.Container{
						{
							Name:            "manager",
							Image:           fmt.Sprintf("%s@%s", tempoOperatorImage, tempoOperatorVersion),
							ImagePullPolicy: corev1.PullIfNotPresent,
							Args: []string{
								"--zap-log-level=info",
								"start",
								"--metrics-tls-cert-dir=/var/run/tls/server/",
							},
							Env: []corev1.EnvVar{
								{Name: "RELATED_IMAGE_TEMPO", Value: fmt.Sprintf("%s@%s", tempoImage, tempoVersion)},
								{Name: "RELATED_IMAGE_TEMPO_QUERY", Value: fmt.Sprintf("%s@%s", tempoQueryImage, tempoQueryVersion)},
								{Name: "RELATED_IMAGE_TEMPO_GATEWAY", Value: fmt.Sprintf("%s@%s", tempoGatewayImage, tempoGatewayVersion)},
								{Name: "RELATED_IMAGE_TEMPO_GATEWAY_OPA", Value: fmt.Sprintf("%s@%s", tempoOPAImage, tempoOPAVersion)},
								{Name: "DISTRIBUTION", Value: "openshift"},
								{Name: "FEATURE_GATES", Value: "openshift.route,openshift.servingCertsService,openshift.oauthProxy,openshift.noAuthWarning,prometheusOperator,observability.metrics.createServiceMonitors,observability.metrics.createPrometheusRules"},
								{Name: "DEFAULT_POD_SECURITY_CONTEXT", Value: "{}"},
							},
							Ports: []corev1.ContainerPort{
								{Name: "webhook-server", ContainerPort: 9443, Protocol: corev1.ProtocolTCP},
								{Name: "https", ContainerPort: 8443, Protocol: corev1.ProtocolTCP},
							},
							Resources: corev1.ResourceRequirements{
								Requests: corev1.ResourceList{
									corev1.ResourceCPU:    resource.MustParse("100m"),
									corev1.ResourceMemory: resource.MustParse("64Mi"),
								},
							},
							SecurityContext: &corev1.SecurityContext{
								AllowPrivilegeEscalation: ptr.To(false),
								Capabilities: &corev1.Capabilities{
									Drop: []corev1.Capability{"ALL"},
								},
							},
							LivenessProbe: &corev1.Probe{
								ProbeHandler: corev1.ProbeHandler{
									HTTPGet: &corev1.HTTPGetAction{
										Path:   "/healthz",
										Port:   intstr.FromInt(8081),
										Scheme: corev1.URISchemeHTTP,
									},
								},
								InitialDelaySeconds: 15,
								PeriodSeconds:       20,
							},
							ReadinessProbe: &corev1.Probe{
								ProbeHandler: corev1.ProbeHandler{
									HTTPGet: &corev1.HTTPGetAction{
										Path:   "/readyz",
										Port:   intstr.FromInt(8081),
										Scheme: corev1.URISchemeHTTP,
									},
								},
								InitialDelaySeconds: 5,
								PeriodSeconds:       10,
							},
							VolumeMounts: []corev1.VolumeMount{
								{
									Name:      "cert",
									MountPath: "/tmp/k8s-webhook-server/serving-certs",
									ReadOnly:  true,
								},
								{
									Name:      "tempo-operator-metrics-cert",
									MountPath: "/var/run/tls/server",
									ReadOnly:  true,
								},
							},
						},
					},
					Volumes: []corev1.Volume{
						{
							Name: "cert",
							VolumeSource: corev1.VolumeSource{
								Secret: &corev1.SecretVolumeSource{
									SecretName:  "tempo-operator-webhook-server-cert",
									DefaultMode: ptr.To(int32(420)),
								},
							},
						},
						{
							Name: "tempo-operator-metrics-cert",
							VolumeSource: corev1.VolumeSource{
								Secret: &corev1.SecretVolumeSource{
									SecretName:  "tempo-operator-metrics",
									DefaultMode: ptr.To(int32(420)),
								},
							},
						},
					},
					TerminationGracePeriodSeconds: ptr.To(int64(10)),
				},
			},
		},
	}
}

// NewTempoServiceAccountControllerManager returns the ServiceAccount for the controller-manager.
func NewTempoServiceAccountControllerManager(namespace string) *corev1.ServiceAccount {
	return &corev1.ServiceAccount{
		TypeMeta: metav1.TypeMeta{
			APIVersion: corev1.SchemeGroupVersion.String(),
			Kind:       "ServiceAccount",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "tempo-operator-controller-manager",
			Namespace: namespace,
			Labels: map[string]string{
				"app.kubernetes.io/managed-by": "rhobs",
				"app.kubernetes.io/name":       "tempo-operator",
				"app.kubernetes.io/part-of":    "tempo-operator",
			},
		},
	}
}

// NewTempoClusterRoleManager returns the ClusterRole for tempo operator manager.
func NewTempoClusterRoleManager() *rbacv1.ClusterRole {
	return &rbacv1.ClusterRole{
		TypeMeta: metav1.TypeMeta{
			APIVersion: rbacv1.SchemeGroupVersion.String(),
			Kind:       "ClusterRole",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: "tempo-operator-manager-role",
			Labels: map[string]string{
				"app.kubernetes.io/managed-by": "rhobs",
				"app.kubernetes.io/name":       "tempo-operator",
				"app.kubernetes.io/part-of":    "tempo-operator",
			},
		},
		Rules: []rbacv1.PolicyRule{
			// Core Kubernetes resources - full CRUD
			{
				APIGroups: []string{""},
				Resources: []string{
					"configmaps",
					"pods",
					"secrets",
					"serviceaccounts",
					"services",
				},
				Verbs: []string{"create", "delete", "get", "list", "patch", "update", "watch"},
			},
			// Core resources - read only
			{
				APIGroups: []string{""},
				Resources: []string{"namespaces"},
				Verbs:     []string{"get", "list", "watch"},
			},
			// PersistentVolumeClaims - read only
			{
				APIGroups: []string{""},
				Resources: []string{"persistentvolumeclaims"},
				Verbs:     []string{"list", "watch"},
			},
			// Events - create and patch only
			{
				APIGroups: []string{""},
				Resources: []string{"events"},
				Verbs:     []string{"create", "patch"},
			},
			// Discovery resources
			{
				APIGroups: []string{"discovery.k8s.io"},
				Resources: []string{"endpointslices"},
				Verbs:     []string{"get", "list", "watch"},
			},
			// Apps resources
			{
				APIGroups: []string{"apps"},
				Resources: []string{"deployments", "statefulsets"},
				Verbs:     []string{"create", "delete", "get", "list", "patch", "update", "watch"},
			},
			{
				APIGroups: []string{"apps"},
				Resources: []string{"deployments/finalizers", "statefulsets/finalizers"},
				Verbs:     []string{"update"},
			},
			// Batch resources
			{
				APIGroups: []string{"batch"},
				Resources: []string{"jobs"},
				Verbs:     []string{"create", "get", "list", "watch"},
			},
			// RBAC resources
			{
				APIGroups: []string{"rbac.authorization.k8s.io"},
				Resources: []string{"clusterrolebindings", "clusterroles", "rolebindings", "roles"},
				Verbs:     []string{"create", "delete", "get", "list", "patch", "update", "watch"},
			},
			// Coordination resources (leader election)
			{
				APIGroups: []string{"coordination.k8s.io"},
				Resources: []string{"leases"},
				Verbs:     []string{"create", "delete", "get", "list", "patch", "update", "watch"},
			},
			// Monitoring resources
			{
				APIGroups: []string{"monitoring.coreos.com"},
				Resources: []string{"prometheusrules", "servicemonitors", "podmonitors"},
				Verbs:     []string{"create", "delete", "get", "list", "patch", "update", "watch"},
			},
			// Prometheus API (for remote write)
			{
				APIGroups:     []string{"monitoring.coreos.com"},
				Resources:     []string{"prometheuses/api"},
				ResourceNames: []string{"k8s"},
				Verbs:         []string{"get", "create", "update"},
			},
			// Metrics API
			{
				APIGroups: []string{"metrics.k8s.io"},
				Resources: []string{"pods"},
				Verbs:     []string{"create", "get"},
			},
			// Grafana resources
			{
				APIGroups: []string{"grafana.integreatly.org"},
				Resources: []string{"grafanadatasources"},
				Verbs:     []string{"create", "delete", "get", "list", "patch", "update", "watch"},
			},
			// Networking resources
			{
				APIGroups: []string{"networking.k8s.io"},
				Resources: []string{"ingresses", "networkpolicies"},
				Verbs:     []string{"create", "delete", "get", "list", "patch", "update", "watch"},
			},
			// OpenShift route resources
			{
				APIGroups: []string{"route.openshift.io"},
				Resources: []string{"routes", "routes/custom-host"},
				Verbs:     []string{"create", "delete", "get", "list", "update", "watch"},
			},
			// OpenShift config resources
			{
				APIGroups: []string{"config.openshift.io"},
				Resources: []string{"dnses"},
				Verbs:     []string{"get", "list", "watch"},
			},
			// OpenShift operator resources
			{
				APIGroups: []string{"operator.openshift.io"},
				Resources: []string{"ingresscontrollers"},
				Verbs:     []string{"get", "list", "watch"},
			},
			// OpenShift cloud credential resources
			{
				APIGroups: []string{"cloudcredential.openshift.io"},
				Resources: []string{"credentialsrequests"},
				Verbs:     []string{"create", "delete", "get", "list", "update", "watch"},
			},
			// Tempo custom resources
			{
				APIGroups: []string{"tempo.grafana.com"},
				Resources: []string{"tempostacks", "tempomonolithics"},
				Verbs:     []string{"create", "delete", "get", "list", "patch", "update", "watch"},
			},
			// Tempo custom resources finalizers
			{
				APIGroups: []string{"tempo.grafana.com"},
				Resources: []string{"tempostacks/finalizers", "tempomonolithics/finalizers"},
				Verbs:     []string{"update"},
			},
			// Tempo custom resources status
			{
				APIGroups: []string{"tempo.grafana.com"},
				Resources: []string{"tempostacks/status", "tempomonolithics/status"},
				Verbs:     []string{"get", "patch", "update"},
			},
			// Authentication and authorization (for webhooks and proxies)
			{
				APIGroups: []string{"authentication.k8s.io"},
				Resources: []string{"tokenreviews"},
				Verbs:     []string{"create"},
			},
			{
				APIGroups: []string{"authorization.k8s.io"},
				Resources: []string{"subjectaccessreviews"},
				Verbs:     []string{"create"},
			},
		},
	}
}

// NewTempoClusterRoleBindingManager returns the ClusterRoleBinding for tempo operator manager.
func NewTempoClusterRoleBindingManager(namespace string) *rbacv1.ClusterRoleBinding {
	return &rbacv1.ClusterRoleBinding{
		TypeMeta: metav1.TypeMeta{
			APIVersion: rbacv1.SchemeGroupVersion.String(),
			Kind:       "ClusterRoleBinding",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: "tempo-operator-manager-rolebinding",
			Labels: map[string]string{
				"app.kubernetes.io/managed-by": "rhobs",
				"app.kubernetes.io/name":       "tempo-operator",
				"app.kubernetes.io/part-of":    "tempo-operator",
			},
		},
		Subjects: []rbacv1.Subject{{
			Kind:      "ServiceAccount",
			Name:      "tempo-operator-controller-manager",
			Namespace: namespace,
		}},
		RoleRef: rbacv1.RoleRef{
			APIGroup: rbacv1.SchemeGroupVersion.Group,
			Kind:     "ClusterRole",
			Name:     "tempo-operator-manager-role",
		},
	}
}

// NewTempoStackEditorClusterRole returns the ClusterRole for tempostack-editor-role.
func NewTempoStackEditorClusterRole() *rbacv1.ClusterRole {
	return &rbacv1.ClusterRole{
		TypeMeta: metav1.TypeMeta{
			APIVersion: rbacv1.SchemeGroupVersion.String(),
			Kind:       "ClusterRole",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: "tempo-tempostack-editor-role",
			Labels: map[string]string{
				"app.kubernetes.io/managed-by":                 "rhobs",
				"app.kubernetes.io/name":                       "tempo-operator",
				"app.kubernetes.io/part-of":                    "tempo-operator",
				"rbac.authorization.k8s.io/aggregate-to-edit":  "true",
				"rbac.authorization.k8s.io/aggregate-to-admin": "true",
			},
		},
		Rules: []rbacv1.PolicyRule{
			{
				APIGroups: []string{"tempo.grafana.com"},
				Resources: []string{"tempostacks"},
				Verbs:     []string{"create", "delete", "get", "list", "patch", "update", "watch"},
			},
			{
				APIGroups: []string{"tempo.grafana.com"},
				Resources: []string{"tempostacks/status"},
				Verbs:     []string{"get"},
			},
		},
	}
}

// NewTempoStackViewerClusterRole returns the ClusterRole for tempostack-viewer-role.
func NewTempoStackViewerClusterRole() *rbacv1.ClusterRole {
	return &rbacv1.ClusterRole{
		TypeMeta: metav1.TypeMeta{
			APIVersion: rbacv1.SchemeGroupVersion.String(),
			Kind:       "ClusterRole",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: "tempo-tempostack-viewer-role",
			Labels: map[string]string{
				"app.kubernetes.io/managed-by":                "rhobs",
				"app.kubernetes.io/name":                      "tempo-operator",
				"app.kubernetes.io/part-of":                   "tempo-operator",
				"rbac.authorization.k8s.io/aggregate-to-view": "true",
			},
		},
		Rules: []rbacv1.PolicyRule{
			{
				APIGroups: []string{"tempo.grafana.com"},
				Resources: []string{"tempostacks"},
				Verbs:     []string{"get", "list", "watch"},
			},
			{
				APIGroups: []string{"tempo.grafana.com"},
				Resources: []string{"tempostacks/status"},
				Verbs:     []string{"get"},
			},
		},
	}
}

// NewTempoMonolithicEditorClusterRole returns the ClusterRole for tempomonolithic-editor-role.
func NewTempoMonolithicEditorClusterRole() *rbacv1.ClusterRole {
	return &rbacv1.ClusterRole{
		TypeMeta: metav1.TypeMeta{
			APIVersion: rbacv1.SchemeGroupVersion.String(),
			Kind:       "ClusterRole",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: "tempo-tempomonolithic-editor-role",
			Labels: map[string]string{
				"app.kubernetes.io/managed-by":                 "rhobs",
				"app.kubernetes.io/name":                       "tempo-operator",
				"app.kubernetes.io/part-of":                    "tempo-operator",
				"rbac.authorization.k8s.io/aggregate-to-edit":  "true",
				"rbac.authorization.k8s.io/aggregate-to-admin": "true",
			},
		},
		Rules: []rbacv1.PolicyRule{
			{
				APIGroups: []string{"tempo.grafana.com"},
				Resources: []string{"tempomonolithics"},
				Verbs:     []string{"create", "delete", "get", "list", "patch", "update", "watch"},
			},
			{
				APIGroups: []string{"tempo.grafana.com"},
				Resources: []string{"tempomonolithics/status"},
				Verbs:     []string{"get"},
			},
		},
	}
}

// NewTempoMonolithicViewerClusterRole returns the ClusterRole for tempomonolithic-viewer-role.
func NewTempoMonolithicViewerClusterRole() *rbacv1.ClusterRole {
	return &rbacv1.ClusterRole{
		TypeMeta: metav1.TypeMeta{
			APIVersion: rbacv1.SchemeGroupVersion.String(),
			Kind:       "ClusterRole",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: "tempo-tempomonolithic-viewer-role",
			Labels: map[string]string{
				"app.kubernetes.io/managed-by":                "rhobs",
				"app.kubernetes.io/name":                      "tempo-operator",
				"app.kubernetes.io/part-of":                   "tempo-operator",
				"rbac.authorization.k8s.io/aggregate-to-view": "true",
			},
		},
		Rules: []rbacv1.PolicyRule{
			{
				APIGroups: []string{"tempo.grafana.com"},
				Resources: []string{"tempomonolithics"},
				Verbs:     []string{"get", "list", "watch"},
			},
			{
				APIGroups: []string{"tempo.grafana.com"},
				Resources: []string{"tempomonolithics/status"},
				Verbs:     []string{"get"},
			},
		},
	}
}

// NewTempoPrometheusRole returns the Role for prometheus.
func NewTempoPrometheusRole(namespace string) *rbacv1.Role {
	return &rbacv1.Role{
		TypeMeta: metav1.TypeMeta{
			APIVersion: rbacv1.SchemeGroupVersion.String(),
			Kind:       "Role",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "tempo-operator-prometheus",
			Namespace: namespace,
			Labels: map[string]string{
				"app.kubernetes.io/managed-by": "rhobs",
				"app.kubernetes.io/name":       "tempo-operator",
				"app.kubernetes.io/part-of":    "tempo-operator",
			},
			Annotations: map[string]string{
				"include.release.openshift.io/self-managed-high-availability": "true",
				"include.release.openshift.io/single-node-developer":          "true",
			},
		},
		Rules: []rbacv1.PolicyRule{
			{
				APIGroups: []string{""},
				Resources: []string{"services", "endpoints", "pods"},
				Verbs:     []string{"get", "list", "watch"},
			},
		},
	}
}

// NewTempoPrometheusRoleBinding returns the RoleBinding for prometheus.
func NewTempoPrometheusRoleBinding(namespace string) *rbacv1.RoleBinding {
	return &rbacv1.RoleBinding{
		TypeMeta: metav1.TypeMeta{
			APIVersion: rbacv1.SchemeGroupVersion.String(),
			Kind:       "RoleBinding",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "tempo-operator-prometheus",
			Namespace: namespace,
			Labels: map[string]string{
				"app.kubernetes.io/managed-by": "rhobs",
				"app.kubernetes.io/name":       "tempo-operator",
				"app.kubernetes.io/part-of":    "tempo-operator",
			},
			Annotations: map[string]string{
				"include.release.openshift.io/self-managed-high-availability": "true",
				"include.release.openshift.io/single-node-developer":          "true",
			},
		},
		Subjects: []rbacv1.Subject{
			{
				Kind:      "ServiceAccount",
				Name:      "prometheus-k8s",
				Namespace: "openshift-monitoring",
			},
		},
		RoleRef: rbacv1.RoleRef{
			APIGroup: rbacv1.SchemeGroupVersion.Group,
			Kind:     "Role",
			Name:     "tempo-operator-prometheus",
		},
	}
}

// NewTempoLeaderElectionRole returns the Role for leader election.
func NewTempoLeaderElectionRole(namespace string) *rbacv1.Role {
	return &rbacv1.Role{
		TypeMeta: metav1.TypeMeta{
			APIVersion: rbacv1.SchemeGroupVersion.String(),
			Kind:       "Role",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "tempo-leader-election-role",
			Namespace: namespace,
			Labels: map[string]string{
				"app.kubernetes.io/managed-by": "rhobs",
				"app.kubernetes.io/name":       "tempo-operator",
				"app.kubernetes.io/part-of":    "tempo-operator",
			},
		},
		Rules: []rbacv1.PolicyRule{
			{
				APIGroups: []string{""},
				Resources: []string{"configmaps"},
				Verbs:     []string{"get", "list", "watch", "create", "update", "patch", "delete"},
			},
			{
				APIGroups: []string{"coordination.k8s.io"},
				Resources: []string{"leases"},
				Verbs:     []string{"get", "list", "watch", "create", "update", "patch", "delete"},
			},
			{
				APIGroups: []string{""},
				Resources: []string{"events"},
				Verbs:     []string{"create", "patch"},
			},
		},
	}
}

// NewTempoLeaderElectionRoleBinding returns the RoleBinding for leader election.
func NewTempoLeaderElectionRoleBinding(namespace string) *rbacv1.RoleBinding {
	return &rbacv1.RoleBinding{
		TypeMeta: metav1.TypeMeta{
			APIVersion: rbacv1.SchemeGroupVersion.String(),
			Kind:       "RoleBinding",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "tempo-leader-election-rolebinding",
			Namespace: namespace,
			Labels: map[string]string{
				"app.kubernetes.io/managed-by": "rhobs",
				"app.kubernetes.io/name":       "tempo-operator",
				"app.kubernetes.io/part-of":    "tempo-operator",
			},
		},
		Subjects: []rbacv1.Subject{
			{
				Kind:      "ServiceAccount",
				Name:      "tempo-operator-controller-manager",
				Namespace: namespace,
			},
		},
		RoleRef: rbacv1.RoleRef{
			APIGroup: rbacv1.SchemeGroupVersion.Group,
			Kind:     "Role",
			Name:     "tempo-leader-election-role",
		},
	}
}

// NewTempoMetricsReaderClusterRole returns the ClusterRole for metrics reader.
func NewTempoMetricsReaderClusterRole() *rbacv1.ClusterRole {
	return &rbacv1.ClusterRole{
		TypeMeta: metav1.TypeMeta{
			APIVersion: rbacv1.SchemeGroupVersion.String(),
			Kind:       "ClusterRole",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: "tempo-operator-metrics-reader",
			Labels: map[string]string{
				"app.kubernetes.io/managed-by": "rhobs",
				"app.kubernetes.io/name":       "tempo-operator",
				"app.kubernetes.io/part-of":    "tempo-operator",
			},
		},
		Rules: []rbacv1.PolicyRule{
			{
				NonResourceURLs: []string{"/metrics"},
				Verbs:           []string{"get"},
			},
		},
	}
}

// NewTempoMetricsService returns the Service for controller manager metrics.
func NewTempoMetricsService(namespace string) *corev1.Service {
	return &corev1.Service{
		TypeMeta: metav1.TypeMeta{
			APIVersion: corev1.SchemeGroupVersion.String(),
			Kind:       "Service",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "tempo-operator-controller-manager-metrics-service",
			Namespace: namespace,
			Labels: map[string]string{
				"app.kubernetes.io/name":      "tempo-operator",
				"app.kubernetes.io/component": "controller",
			},
			Annotations: map[string]string{
				// OpenShift automatically generates and mounts the certificate
				"service.beta.openshift.io/serving-cert-secret-name": "tempo-operator-metrics",
			},
		},
		Spec: corev1.ServiceSpec{
			Selector: map[string]string{
				"app.kubernetes.io/name":      "tempo-operator",
				"app.kubernetes.io/component": "controller",
			},
			Ports: []corev1.ServicePort{
				{
					Name:       "https",
					Protocol:   corev1.ProtocolTCP,
					Port:       8443,
					TargetPort: intstr.FromString("https"),
				},
			},
		},
	}
}

// NewTempoClusterMonitoringViewBinding returns the ClusterRoleBinding for cluster-monitoring-view.
// This binds the OpenShift built-in cluster-monitoring-view ClusterRole to the tempo-operator-controller-manager ServiceAccount.
func NewTempoClusterMonitoringViewBinding(namespace string) *rbacv1.ClusterRoleBinding {
	return &rbacv1.ClusterRoleBinding{
		TypeMeta: metav1.TypeMeta{
			APIVersion: rbacv1.SchemeGroupVersion.String(),
			Kind:       "ClusterRoleBinding",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: "tempo-operator-manager-rolebinding-cluster-monitoring-view",
			Labels: map[string]string{
				"app.kubernetes.io/managed-by": "rhobs",
				"app.kubernetes.io/name":       "tempo-operator",
				"app.kubernetes.io/part-of":    "tempo-operator",
			},
		},
		Subjects: []rbacv1.Subject{
			{
				Kind:      "ServiceAccount",
				Name:      "tempo-operator-controller-manager",
				Namespace: namespace,
			},
		},
		RoleRef: rbacv1.RoleRef{
			APIGroup: rbacv1.SchemeGroupVersion.Group,
			Kind:     "ClusterRole",
			Name:     "cluster-monitoring-view",
		},
	}
}

// NewTempoWebhookService returns the Service for webhook server.
func NewTempoWebhookService(namespace string) *corev1.Service {
	return &corev1.Service{
		TypeMeta: metav1.TypeMeta{
			APIVersion: corev1.SchemeGroupVersion.String(),
			Kind:       "Service",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "tempo-operator-webhook-service",
			Namespace: namespace,
			Annotations: map[string]string{
				// OpenShift automatically generates and mounts the certificate
				"service.beta.openshift.io/serving-cert-secret-name": "tempo-operator-webhook-server-cert",
			},
		},
		Spec: corev1.ServiceSpec{
			Selector: map[string]string{
				"app.kubernetes.io/name":      "tempo-operator",
				"app.kubernetes.io/component": "controller",
			},
			Ports: []corev1.ServicePort{
				{
					Port:       443,
					Protocol:   corev1.ProtocolTCP,
					TargetPort: intstr.FromInt(9443),
				},
			},
		},
	}
}
